### ISSUE TITLE
Error in utils::browserURL(appUrl)

### ISSUE THREAD

**Issue by SiyiWanggou** [davidaknowles/leafcutter#101]
I prepared the files that run_leafviz.R need.
However, when I use run_leafviz.R to visualize the data, I get the error information as below:

Error in utils::browserURL(appUrl):
 'browser' must be a non-empty character string

Execution halted

Dose anybody know what's problem with this? How can I fix this issue?

**Comment by jackhump** [comment]
Hi!
Can you tell us what version of R, operating system and browser you're running this on? I only ever tested this on OS X with Google Chrome set as the default browser. And the scripts should be working with R > 3.4.4

**Comment by davidaknowles** [comment]
Closing this for now due to reactivity. Please reopen if it comes up again.
