### ISSUE TITLE
Figures cannot be loaded in tutorial

### ISSUE THREAD

**Issue by chenkenbio** [davidaknowles/leafcutter#105]
Hello!
Thank you for your wonderful work. But I found that some figures in the tutorial (http://davidaknowles.github.io/leafcutter/articles/Usage.html and http://davidaknowles.github.io/leafcutter/articles/Visualization.html) can not be seen. Would you please fix them?
Thank you!

**Comment by davidaknowles** [comment]
This is fixed. Think they got lost when the stan package structure changed.
