### ISSUE TITLE
Genes without gene_name

### ISSUE THREAD

**Issue by hmontenegro** [davidaknowles/leafcutter#108]
Ensembl GTFs can have genes without **gene_name** attribute, thus `gtf_to_exons.R` creates some exons without **gene_name**. `leafcutter_ds.R` then errors out with:

`Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, : line 1 did not have 5 elements`

A workaround is, when creating the `exons.txt.gz` file, to assign **gene_id** to the exon if there is no **gene_name** attribute.

**Comment by hmontenegro** [comment]
Proposed #109 as fix.

**Comment by davidaknowles** [comment]
I've merged this, thanks for the contribution!
