### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by RHReynolds** [davidaknowles/leafcutter#111]
Hi,

I've been trying to install leafcutter in RStudio using the recommended devtools method advised (https://davidaknowles.github.io/leafcutter/articles/Installation.html). Unfortunately, there appears to be an error that primarily relates to the creation of the following file: `stan_files/bb_glm.o`. The error message I receive is quite long, so I have attached here: [leafcutter_installation_error.txt](https://github.com/davidaknowles/leafcutter/files/3493668/leafcutter_installation_error.txt)

I have attempted a couple of different things to correct the error, including:
1. Installing leafcutter using the "From source" tutorial mentioned in the installation guide. I got the same error as before.
2. As I run RStudio on RStudio Server, I wondered if this error might be due to my own local user-specific libraries. Thus, I asked two of my colleagues who do not have leafcutter installed, but who run RStudio on the same server (albeit with different user names and thus different user-specific libraries), to try installing leafcutter using the devtools method. Like me, they updated any suggested packages when prompted at the beginning of the installation and experienced the same issue. 
3. One colleague (also on the same server) already had leafcutter installed (v0.2.8). They successfully installed it in ~March 2019 using the devtools method and have not had any issues since. In a bit of a last ditch attempt, I compared our user-specific package versions and where they differed (e.g. he had RStan v.2.18.2, while I had v2.19.2) and reverted mine to the same version as his. I attempted installation again (via devtools) and still no luck.

I can see there are others who have had similar installation issues, although do not appear to have quite the same error message I have, hence the new issue. I've also attached my session info, in case you need that (
[Session_info.txt](https://github.com/davidaknowles/leafcutter/files/3493713/Session_info.txt)).

Thanks in advance for any and all help!

Best,
Regina

**Comment by davidaknowles** [comment]
Can you try
```
devtools::install_github("stan-dev/rstantools")
devtools::install_github("davidaknowles/leafcutter/leafcutter", ref = "stanfixagain")
```
please? This works for me on R 3.6.1 so fingers crossed it'll be ok for you on R3.4 also.

**Comment by RHReynolds** [comment]
Hi David,
This fix worked. Thanks very much!!

**Comment by davidaknowles** [comment]
Great. My worry now is just whether this will work on older R versions! I guess for now I'll just document this.

**Comment by fbearoff** [comment]
I am having the same issue on R 3.6.1. I've tried the various fixes mentioned with no luck.  Install log here 
[install_log.txt](https://github.com/davidaknowles/leafcutter/files/3601461/install_log.txt) Session info here [Session_info.txt](https://github.com/davidaknowles/leafcutter/files/3601472/Session_info.txt)

Thanks

**Comment by davidaknowles** [comment]
@fbearoff : 
can you confirm `rstan` and `rstantools` are successfully installed and loadable and what versions you have? 
What's in your `~/.R/Makevars`? 
What version of `gcc` is on your system? 

Thanks.

**Comment by fbearoff** [comment]
Thanks David,

$ gcc --version
gcc (GCC) 4.9.1

Makevars:
CXX14FLAGS=-O3 -march=native -mtune=native -fPIC
CXX14=g++ -std=c++11

other attached packages:
[1] rstantools_2.0.0.9000 rstan_2.19.2          ggplot2_3.2.1
[4] StanHeaders_2.19.0

Frank

**Comment by gulipeng17** [comment]
> Thanks David,
> 
> $ gcc --version
> gcc (GCC) 4.9.1
> 
> Makevars:
> CXX14FLAGS=-O3 -march=native -mtune=native -fPIC
> CXX14=g++ -std=c++11
> 
> other attached packages:
> [1] rstantools_2.0.0.9000 rstan_2.19.2 ggplot2_3.2.1
> [4] StanHeaders_2.19.0
> 
> Frank

have you solve the problem，sir？

**Comment by fbearoff** [comment]
I never got this to work on our CentOS 6.0 environment. I just ran the scripts on our cluster and had to do the bits in R using my local console running Arch.

**Comment by fbearoff** [comment]
> 
> 
> > Thanks David,
> > $ gcc --version
> > gcc (GCC) 4.9.1
> > Makevars:
> > CXX14FLAGS=-O3 -march=native -mtune=native -fPIC
> > CXX14=g++ -std=c++11
> > other attached packages:
> > [1] rstantools_2.0.0.9000 rstan_2.19.2 ggplot2_3.2.1
> > [4] StanHeaders_2.19.0
> > Frank
> 
> have you solve the problem，sir？

I never got this to work on our CentOS 6.0 environment. I just ran the scripts on our cluster and had to do the bits in R using my local console running Arch.
