### ISSUE TITLE
differential_splicing.R error

### ISSUE THREAD

**Issue by Arkosen** [davidaknowles/leafcutter#112]
I have been trying to run leafcutter differential_splicing.R on a cluster count matrix and I keep getting the following error. I cant make much sense of it so I was wondering if anybody can help.

Error in file("/dev/null", open = "wt") : cannot open the connection
In addition: Warning message:
In file("/dev/null", open = "wt") :
  cannot open file '/dev/null': No such file or directory

**Comment by jackhump** [comment]
what operating system are you trying to run this on?  
/dev/null is a special device file on linux/unix/macOS systems - see here: https://en.wikipedia.org/wiki/Null_device
Can you verify that the computer you're using has a /dev/null ?

**Comment by davidaknowles** [comment]
I suppose this might be a problem on Windows. We redirect rstan's excessive output to /dev/null, in theory I think we should be able to do something similar on Windows using `nul`: https://stackoverflow.com/questions/313111/is-there-a-dev-null-on-windows.

**Comment by AlexWeinreb** [comment]
About this issue: it appears on Windows when running the R function `differential_splicing()` with the option `debug=FALSE`.  It can be avoided by setting `debug=TRUE`.

This is due to the following piece of code:
 ``` 
if (!debug) {
    zz <- file("/dev/null", open = "wt")
    sink(zz)
    sink(zz, type = "message")
  }
```

And would be solved using `nullfile()` instead:
``` 
if (!debug) {
    zz <- file(nullfile(), open = "wt")
    sink(zz)
    sink(zz, type = "message")
  }
```
