### ISSUE TITLE
Intron clustering issue

### ISSUE THREAD

**Issue by AlanMonziani** [davidaknowles/leafcutter#114]
Hello, I am trying to run the intron clustering script (leafcutter_cluster.py), using either the test files and my own. In both cases I keep getting this error:

Traceback (most recent call last):
  File "clustering/leafcutter_cluster.py", line 489, in <module>
    main(options, libl)
  File "clustering/leafcutter_cluster.py", line 11, in main
    pool_junc_reads(libl, options)
  File "clustering/leafcutter_cluster.py", line 58, in pool_junc_reads
    fout = file(outFile, 'w')
NameError: name 'file' is not defined

Junc files are scanned correctly, as a list of messages with the found files is being displayed as the script goes on. Any idea of which is the cause?

Many thanks

**Comment by goldenflaw** [comment]
Please use python 2.7.

Best,
Yang

**Comment by AlanMonziani** [comment]
It worked, thanks! Our grid had 3.7 as default and I didn't even noticed.
