### ISSUE TITLE
Can we get types of alternative splicing events based on your output result?

### ISSUE THREAD

**Issue by itszhengan** [davidaknowles/leafcutter#115]
I want to get specific type of alternative splicing event such as intron retention, exon skipping, etc. Can I calculate what I want based on your output?  Thanks!

Zheng

**Comment by jackhump** [comment]
Leafcutter does not quantify intron retention due to only counting splice junction reads.

If you're interested in classifying and quantifying cassette exon inclusion see here: https://groups.google.com/forum/#!topic/leafcutter-users/nX_2qDq37zY

**Comment by jackhump** [comment]
Further answer here: #120
