### ISSUE TITLE
Outputted introns 1 bp longer than inputted junctions

### ISSUE THREAD

**Issue by RHReynolds** [davidaknowles/leafcutter#117]
Hi,

I noticed that introns outputted after leafcutter clustering appear to have +1 bp added to their ends, unlike the input junction files. I wondered why that might be? I am raising this issue as it can cause problems when attempting to match introns back to existing reference annotation if the user is unaware of the +1. My python is a bit rusty, but I think it might be due to the following code `A, B = int(A), int(B)+1` in line 51 of the leafcutter_cluster.py script. 

Best,
Regina

**Comment by goldenflaw** [comment]
Hi Regina,

You should be using leafcutter_cluster_regtools now. But to answer your
questions, there are some discrepancies between what the coordinates that
is in the (now defunct) .junc files and the ensembl annotations, we tested
this and the +1 actually helps the matching.

Best,
Yang

**Comment by RHReynolds** [comment]
Thanks Yang for your quick response. I was not aware that I should be using the leafcutter_cluster_regtools -- you may wish to update the usage documentation (https://davidaknowles.github.io/leafcutter/articles/Usage.html), which currently suggests users use leafcutter_cluster. I'll be sure to try with the new clustering script. Thanks again!
