### ISSUE TITLE
which pipeline  to prepare data should I use?

### ISSUE THREAD

**Issue by QuanLG** [davidaknowles/leafcutter#118]
Hi,
         Recently  I  noticed that there are tow pipeline for leafcutter to prepare data as shown in the figure. I don't know which is the most suitable to use.
And,the pipeline on web, when I use the code  'leafcutter_cluster.py' , the parameter '--strand' should I set it to True？
![pipeline1](https://user-images.githubusercontent.com/58326238/69926292-d82fba80-14ee-11ea-9ccd-5a7d16e3e08c.png)

![pipeline2](https://user-images.githubusercontent.com/58326238/69926298-dfef5f00-14ee-11ea-9c9a-05d0ebdb5b38.png)

**Comment by goldenflaw** [comment]
The regtools version speeds the pipeline considerably. You can use strand
if you care about it but it optional.

Best
Yang

**Comment by QuanLG** [comment]
I use the regtools to prepare the bam from hista2,then I use the   'leafcutter_cluster_regtools.py ' to  cluster ,but this is a erro for example :

scanning /mnt/workShop/08_AS_5/leafcutter/2_4_out/test_regtools/bam/R19018652-20190417-NGS-1-SP1904141846_combined.sorted.bam.junc2...
scanning /mnt/workShop/08_AS_5/leafcutter/2_4_out/test_regtools/bam/R19028051-20190618-NGS-1-SP1906071999_combined.sorted.bam.junc2...
scanning /mnt/workShop/08_AS_5/leafcutter/2_4_out/test_regtools/bam/R19028051-20190618-NGS-1-SP1906072001_combined.sorted.bam.junc2...
scanning /mnt/workShop/08_AS_5/leafcutter/2_4_out/test_regtools/bam/R19034797-20190801-NGS-1-SP1907152069_combined.sorted.bam.junc2...
scanning /mnt/workShop/08_AS_5/leafcutter/2_4_out/test_regtools/bam/R19036417-20190815-NGS-1-SP1905021937_combined.sorted.bam.junc2...
Parsing...
GL000200.1:?..Traceback (most recent call last):
  File "/home/opt/leafcutter/clustering/leafcutter_cluster_regtools.py", line 534, in <module>
    main(options, libl)
  File "/home/opt/leafcutter/clustering/leafcutter_cluster_regtools.py", line 14, in main
    pool_junc_reads(libl, options)
  File "/home/opt/leafcutter/clustering/leafcutter_cluster_regtools.py", line 72, in pool_junc_reads
    clu = cluster_intervals(read_ks)[0]
  File "/home/opt/leafcutter/clustering/leafcutter_cluster_regtools.py", line 337, in cluster_intervals
    current = E[0]
IndexError: list index out of range

**Comment by goldenflaw** [comment]
Please see if there are weird chromosomes without any junctions.

Best,
Yang

**Comment by QuanLG** [comment]
thanks Yang.
I remove the 'GL00* ' chromosomes ,the 'leafcutter_cluster_regtools.py' can cluster . 
And ,I want to know if I  need to use samtools to filter reads first,then use the regtools to find junction reads.

**Comment by goldenflaw** [comment]
This entirely depends on your application. If you think that some reads
need to be filtered out, you should do that first.

Best,
Yang

**Comment by QuanLG** [comment]
I use the  'leafcutter_cluster_regtools.py' to cluster ，then I use the  'leafcutter_ds.R' to differential splicing analysis and use the 'prepare_results.R ' to catch  result.
        I extract the clusters information form 'RData' as follows,and find a problem
"clu_9280_+"    4       "chr6:29912393-29912840"        "HLA-A" "cryptic"       0.000108
"clu_14342_-"   21      **"chr12:125396517-125398114"**     **"."**     "annotated"     0.000149
"clu_17618_?"   25      "chr16:22545157-22547336"       "."     "annotated"     0.000158
"clu_6660_+"    3       "chr8:59465862-59477581"        "SDCBP" "annotated"     0.000158
"clu_637_+"     9       "chr17:7737668-7748219" "KDM6B" "cryptic"       0.000221
"clu_17821_-"   7       "chr20:57477802-57557196"       "."     "annotated"     0.000257
"clu_11498_+"   37      "chr14:22573674-23016447"       "TRAV24"        "cryptic"       0.000471
"clu_504_+"     18      "chr20:61444552-61444913"       "."     "annotated"     0.000532
"clu_13587_+"   3       "chr7:80290526-80293722"        "CD36"  "annotated"     0.000538
"clu_10122_-"   10      "chr11:62293215-62299267"       "."     "annotated"     0.000674
"clu_847_+"     5       "chr17:41158985-41165064"       "IFI35" "cryptic"       0.000837
"clu_14202_-"   16      "chr12:109017303-109017664"     "."     "annotated"     0.000953
"clu_3608_-"    8       "chr22:23237766-23264978"       "."     "annotated"     0.000953
"clu_18512_+"   4       "chr11:32605475-32611093"       "EIF3M" "annotated"     0.00193
"clu_1175_+"    8       "chr17:79413585-79476998"       "."     "annotated"     0.00233
"clu_14676_+"   5       "chr1:43159194-43162851"        "YBX1"  "cryptic"       0.00251
"clu_11103_-"   10      "chr14:106236323-106237006"     "IGHG3" "cryptic"       0.00251
"clu_18016_-"   18      "chr2:70017058-70031641"        "."     "annotated"     0.00294
"clu_11104_-"   5       "chr14:106303493-106306703"     "IGHD"  "cryptic"       0.00427
"clu_3852_-"    28      "chr1:665184-675509"    "."     "annotated"     0.00446
"clu_462_+"     3       "chr20:48892272-48894028"       "RP11-290F20.3" "cryptic"       0.00446
**"clu_9873_?"**    10      **"chr12:125396517-125398114"**     **"."**     "annotated"     0.00521
"clu_1765_-"    5       "chr17:62777661-62781340"       "PLEKHM1P"      "cryptic"       0.00523

**Comment by jackhump** [comment]
Dear QuanLG, apologies for the delay. 

The "." here is due to none of the junctions in the cluster matching any known genes in your annotation.
