### ISSUE TITLE
how to get different categories of splicing events in the result

### ISSUE THREAD

**Issue by sjtuyf** [davidaknowles/leafcutter#120]
Hi, thanks for your great software leafcutter. I have finished all the step of the leafcutter using R-leafcutter. And the result file include 'leafcutter_ds_cluster_significance.txt','leafcutter_ds_effect_sizes.txt'. From that file, we can know which cluster has the splicing event.  However, we also want to know the catagories of splicing events in the result, such as 
“annotated” or “cryptic”, and also the 5' annotated,3' annotated,5' missing,3' missing, and son on. 
I have seen the categories in your published paper. However, I have no idea about my result.
I do not know which file also need to combine, and which softwares I should use to get the information of splicing events in the result file.
    So I really need your help.
    Good luck  to you and hope to your reply.

Best
Yafei

**Comment by goldenflaw** [comment]
Hello, unfortunately what we used is ad hoc and so it is not currently
available.

Best,
Yang

**Comment by sjtuyf** [comment]
Thanks for your reply.
   That means we can get the categories in your case, but now the categories of mis-spliced intron clusters will not available by leafcutter.
However, some papers shows the categories of mis-spliced intron clusters are available by leafcutter. Below are some examples，1) Gandal M J , Zhang P , Hadjimichael E , et al. Transcriptome-wide isoform-level dysregulation in ASD, schizophrenia, and bipolar disorder[J]. Science, 2018, 362(6420).
2)Raj T, Li Y I, Wong G, et al. Integrative transcriptome analyses of the aging brain implicate altered splicing in Alzheimer’s disease susceptibility[J]. Nature genetics, 2018, 50(11): 1584.
So do you have some suggestions about how to get the categories of mis-spliced intron clusters after the analysis of leafcutter, or other comments?
   Another question is anout the installation,。
   I used the command "git clone https://github.com/davidaknowles/leafcutter" to download the package in the linux, but when I run the run_leafviz.R, the error imply that some other packages are also needed.
   And I also try to install the package in Rstudio in the version of 3.3.2, and run the command 
   "> devtools::install_github("davidaknowles/leafcutter/leafcutter")
Error in readRDS(pfile) : 
  cannot read workspace version 3 written by R 3.6.1; need R 3.5.0 or newer" 
   The error imply the R version I used is old. But according the instruction "R (version 3.3.3, earlier versions may be OK)" ,the old version is better. So it make me very depressed of the installation.
   So which is the best way to install the softwares? using linux, window or Mac, and which version of R is the most suitable, and which command is the best to install the softwares.  
   I am sorry I have so many questions. But it takes so long time to deal with these questions. So I really need your help，and thanks again.
   Good luck to you.

Best 
Yafei

**Comment by jackhump** [comment]
Dear Yafei,

I can't comment on reference 2) but I know from the supplementary material for reference 1) the categories of splicing event were determined by looking at each event by eye in the leafviz shiny app. Which for 100 or so events wouldn't be so bad 😄. By eye you should be able to figure out cassette exons, alternate 5' and 3' splice sites and mutually exclusive exons. But bear in mind that with the default filter settings most clusters identified by leafcutter will not neatly fit  into a single category and will instead be complex.

That said, I have written a script to find cassette exons and determine their directions - see here: https://groups.google.com/forum/#!topic/leafcutter-users/nX_2qDq37zY

As for installation, I currently have leafcutter installed both on linux and mac with R 3.6.0 using 

```
install.packages("remotes")
remotes::install_github("stan-dev/rstantools")
remotes::install_github("davidaknowles/leafcutter/leafcutter", ref = "stanfixagain")
```

**Comment by sjtuyf** [comment]
OK, I got it.Thanks for your detailed explanation.
Thanks again.

Best
Yafei


----- 原始邮件 -----
发件人: "Jack Humphrey" <notifications@github.com>
收件人: "davidaknowles/leafcutter" <leafcutter@noreply.github.com>
抄送: "sjtuyf" <sjtuyf@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期一, 2020年 1 月 06日 下午 10:37:22
主题: Re: [davidaknowles/leafcutter] how to get different categories of splicing events in the result (#120)

Dear Yafei,



I can't comment on reference 2) but I know from the supplementary material for reference 1) the categories of splicing event were determined by looking at each event by eye in the leafviz shiny app. Which for 100 or so events wouldn't be so bad 😄. By eye you should be able to figure out cassette exons, alternate 5' and 3' splice sites and mutually exclusive exons. But bear in mind that with the default filter settings most clusters identified by leafcutter will not neatly fit  into a single category and will instead be complex.



That said, I have written a script to find cassette exons and determine their directions - see here: https://groups.google.com/forum/#!topic/leafcutter-users/nX_2qDq37zY



As for installation, I currently have leafcutter installed both on linux and mac with R 3.6.0 using 



```

install.packages("remotes")

remotes::install_github("stan-dev/rstantools")

remotes::install_github("davidaknowles/leafcutter/leafcutter", ref = "stanfixagain")

```
