### ISSUE TITLE
any plans to separate the leafcutter analysis package from a visualization package?

### ISSUE THREAD

**Issue by andrewejaffe** [davidaknowles/leafcutter#125]
I might be a minority user, but I have a Windows laptop with access to a pretty powerful Linux computing cluster. I ran all of the various Leafcutter analyses on the cluster, but shiny doesn't work really well on it. I therefore wanted to be able to visualize the exported leafCutter differential splicing results on my Windows computer, but am unable to install Leafcutter due to various dependency issues, like `doMC`, which cannot be installed. I imagine that the Shiny visualization app itself doesn't really need much of these functions, so I was wondering if there were any ways to create a more streamlined visualization package that is different from the analysis package that can run on any system. 
We have done this in the past for some of our Bioconductor packages:
https://bioconductor.org/packages/release/bioc/html/derfinder.html &
https://bioconductor.org/packages/release/bioc/html/derfinderPlot.html

**Comment by jackhump** [comment]
Hi Andrew! This is definitely on our (admittedly very long and overdue) to-do list. You're right, the leafviz app only requires a couple of functions from the leafcutter R codebase and so could be split out into a separate R package.
 Perhaps this is something we could collaborate on with someone in your lab?

**Comment by jackhump** [comment]
Hi Andrew,

I finally got round to doing this - I've split off the necessary functions into a standalone R package. Hopefully I'll be able to maintain this a little better than I have been in the past:

https://github.com/jackhump/leafviz

I don't have access to a Windows machine here to test it out on, but it installed and ran successfully on a clean R install on my Mac.
