### ISSUE TITLE
Illegal instruction error with leafcutter_ds.R

### ISSUE THREAD

**Issue by fserluca** [davidaknowles/leafcutter#126]
I'm having issues running leafcutter now that our operating system has been changed.
The leafcutter_ds.R script fails to execute properly with the new CentOS7 configuration and I am getting an illegal instruction error.

All scripts that are used before the differential splicing step (bam>junc conversion, clustering) worked fine.
All scripts worked well on the previous OS (RedHat6). Installation of leafcutter and the required R libraries using the new OS also executed fine.
Pasted below are the output from leafcutter_ds.R, and the OS and module information.
Has anyone run into this type of issue before? Any help would be much appreciated.

Terminal output:

Loading required package: Rcpp
Loading counts from ./ClusterPyOut_perind_numers.counts.gz
Loading metadata from RESULTS_6m_27m/test_diff_introns.txt
Encoding as 0_6m =0, 1_27m =1
Loading required package: doMC
Loading required package: foreach
Loading required package: iterators
Loading required package: parallel
Settings:
$output_prefix
[1] "RESULTS_6m_27m/ds"

$max_cluster_size
[1] Inf

$min_samples_per_intron
[1] 3

$min_samples_per_group
[1] 3

$min_coverage
[1] 20

$timeout
[1] 30

$num_threads
[1] 1

$exon_file
[1] "/da/Projects/Leafcutter_RESOURCES/rn6_annotation_files/LeafViz_rn6_UCSC_all_exons.txt.gz"

$init
[1] "smart"

$seed
[1] 12345

$help
[1] FALSE

Running differential splicing analysis...
Illegal instruction

OS information:

LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core)
Release:        7.4.1708
Codename:       Core

Module information:

Currently Loaded Modules:
GCCcore/6.4.0                    
binutils/2.28-GCCcore-6.4.0      
GCC/6.4.0-2.28                   
numactl/2.0.11-GCCcore-6.4.0     
hwloc/1.11.8-GCCcore-6.4.0       
OpenMPI/2.1.2-GCC-6.4.0-2.28     
OpenBLAS/0.2.20-GCC-6.4.0-2.28   
gompi/2018a                      
FFTW/3.3.7-gompi-2018a  
ScaLAPACK/2.0.2-gompi-2018a-OpenBLAS-0.2.20
SAMtools/1.9-foss-2018a
foss/2018a
Emacs/26.2-foss-2018a
Java/1.8.0_162
R/3.6.0-foss-2018a
rstudio/1.2.1335-R-3.6.0
BEDTools/2.27.1-foss-2018a
SQLite/3.24.0-foss-2018a
Python/2.7.14-foss-2018a

**Comment by jackhump** [comment]
Hi, was this ever resolved?

**Comment by fserluca** [comment]
Yes, it wasn’t an issue with LC. This ticket can be closed.
Best,
Fabrizio
