### ISSUE TITLE
No plots come out in splicing event visualisation and gene level visualisation by using shiny app 

### ISSUE THREAD

**Issue by feiyang555** [davidaknowles/leafcutter#128]
Hi all,

I have problem with the last step to visualise the example data in shiny app. The script I run :
leafviz/run_leafviz.R  ./leafvis_example/Brain_vs_Heart_results.Rdata

But I couldn't get the plots in splicing event visualisation and gene level visualisation. Please see blew. It seems that it is still running, but after half hour, still no plots came out. By the way, I am using R/3.6.0. 

Hope I can get your advice : ) 

Many thanks, 

Fei 

<img width="880" alt="Screen Shot 2020-03-12 at 11 14 17 am" src="https://user-images.githubusercontent.com/59793400/76484453-c72f0780-6454-11ea-9429-f32a1be735fa.png">
<img width="1413" alt="Screen Shot 2020-03-12 at 11 14 32 am" src="https://user-images.githubusercontent.com/59793400/76484464-d01fd900-6454-11ea-8a21-79f82f75f50a.png">

**Comment by jackhump** [comment]
Hi Fei,

what browser and operating system are you using? We only ever tested LeafViz on Mac OSX and Google Chrome. 
Can you verify that you're clicking the rows in the "Differential Splicing Events (clusters)" table?

**Comment by feiyang555** [comment]
Hi Jack,&nbsp;


Thanks very much for your quick response. I am using the google chrome on my Mac. I can click and select the row and move to the next page in the table, but nothing came out in the plot area.
Please ley me know what information you need.&nbsp;


Many thanks,&nbsp;


Fei&nbsp;



发自我的iPhone


------------------ Original ------------------

**Comment by jackhump** [comment]
Honestly Fei I have no idea, that's a very strange error. When you click the rows in the table does anything happen on your terminal? It should output something each time you click a row.

**Comment by feiyang555** [comment]
Hi Jack,

Thanks very much. It is my mistake. I did not click the row, so the plots didn't come out. Once I tried just know and click the each row in the table, the plots in both Splicing event visualization and Gene-level visualization all show up, and it also outputs something on terminal.

But I also have another question, there are some weird clusters in my *_perind.counts.gz file which could not be recognised  by the prepare_phenotype_table.py and output error like this ValueError: invalid literal for int() with base 10: 'KI270733.1' . After I removed those 909 clusters among all 265844 clusters, this step ran successfully. I am wondering why I have  those clusters ? And is this reasonable if I remove them even most of the values for those clusters are 0?  I also saw _NA at the end of each cluster in my file, but I look at other people's *_perind.counts.gz, no such a _NA, is this a matter as well? I ran the example data, and the example_perind.counts.gz also has _NA at the end of each cluster. By the way, I am using the bam2junc.sh to get junc files. And my bam files are created by the HISAT2 V2.0.5 
Please see some of those weird clusters below:
KI270731.1:55803:66310:clu_1_NA 
KI270731.1:59648:66310:clu_1_NA
GL000008.2:173643:173838:clu_63614_NA
GL000194.1:53862:54678:clu_47741_NA
KI270706.1:102960:113533:clu_26566_NA
KI270706.1:108642:113533:clu_26566_NA
KI270731.1:78982:79379:clu_4_NA
KI270731.1:78982:80024:clu_4_NA
KI270733.1:118322:139918:clu_4043_NA
KI270733.1:121096:139918:clu_4043_NA
MT:1018:1384:clu_57994_NA
MT:1037:1185:clu_57995_NA
MT:1042:1100:clu_57993_NA
MT:1042:1136:clu_57993_NA
X:10006510:10063445:clu_32755_NA
X:10014782:10063445:clu_32755_NA

Many thanks,

Fei

**Comment by jackhump** [comment]
Dear Fei.

There are two issues here. The first is due to non-chromosome contigs in your genome build. Add the `--checkchrom` to your leafcutter_cluster_regtools.py step and these will be ignored. 

The second is the `_NA` term at the end of the cluster ID refers to the strand of your junctions. The value is NA when the junctions are not provided a strand. You should be using `regtools junction extract` to generate your junction files and you need to specify whether your libraries were stranded or not (see regtools documentation).

**Comment by feiyang555** [comment]
Dear Jack,&nbsp;


Thanks very much for your explanation.&nbsp;


I tried the regtools method to extract junctions, but got the error in the intron clustering step-index out of the range which is same as other people have posted recently. So I stopped trying the regtools:(&nbsp;


Do you have any idea to solve that error when do the clustering intron analysis?&nbsp;
Many thanks,&nbsp;
Fei&nbsp;

发自我的iPhone


------------------ Original ------------------

**Comment by jackhump** [comment]
make sure you're using leafcutter_cluster_regtools.py and use the --checkchrom flag.

**Comment by feiyang555** [comment]
Thanks Jack,&nbsp;
I will try this tomorrow and will let you know by that time:)
Cheers,&nbsp;


Fei

发自我的iPhone


------------------ Original ------------------

**Comment by jackhump** [comment]
Dear Fei, did this strategy work? Please let me know.

**Comment by feiyang555** [comment]
Dear Jack, 

Thanks very much. I tried the regtools method to extract the junctions, then clustered them by using the leafcutter_cluster_regtools.py with the added --checkchrom flag, finally it succeeded. 

Best regards,

Fei
