### ISSUE TITLE
weird clusters (KI270731.1:59648:66310:clu_1_NA) in my  *_perind.counts.gz file 

### ISSUE THREAD

**Issue by feiyang555** [davidaknowles/leafcutter#129]
Hi All,

Thanks for your effort to develop such a good tool. 

But there are some weird clusters in my *_perind.counts.gz file which could not be recognised by the prepare_phenotype_table.py and output error is like this ValueError: invalid literal for int() with base 10: 'KI270733.1' . After I removed those 909 clusters among all 265844 clusters, this step ran successfully. I am wondering why I have those clusters ? And is this reasonable if I remove them even most of the values for those clusters are 0? I also saw _NA at the end of each cluster in my file, but I look at other people's *_perind.counts.gz, no such a _NA, is this a matter as well? I ran the example data, and the example_perind.counts.gz also has _NA at the end of each cluster. By the way, I am using the bam2junc.sh to get junc files. And my bam files are created by the HISAT2 V2.0.5
Please see some of those weird clusters below:
KI270731.1:55803:66310:clu_1_NA
KI270731.1:59648:66310:clu_1_NA
GL000008.2:173643:173838:clu_63614_NA
GL000194.1:53862:54678:clu_47741_NA
KI270706.1:102960:113533:clu_26566_NA
KI270706.1:108642:113533:clu_26566_NA
KI270731.1:78982:79379:clu_4_NA
KI270731.1:78982:80024:clu_4_NA
KI270733.1:118322:139918:clu_4043_NA
KI270733.1:121096:139918:clu_4043_NA
MT:1018:1384:clu_57994_NA
MT:1037:1185:clu_57995_NA
MT:1042:1100:clu_57993_NA
MT:1042:1136:clu_57993_NA
X:10006510:10063445:clu_32755_NA
X:10014782:10063445:clu_32755_NA

Many thanks,

Fei

**Comment by goldenflaw** [comment]
These are from reads that map to the contigs KI.... and on the
mitochondrial and X chromosomes. I would suggest you remove all of these
before proceeding.

Best,
Yang

**Comment by feiyang555** [comment]
Hi Yang,&nbsp;
Thanks very much for your explanations, and I really appreciate:)
Would you please have a look at the issue I posted just know? It is about the terminal output for leafcutter.df.R？&nbsp;


Best wishes,
Fei&nbsp;



发自我的iPhone


------------------ Original ------------------

**Comment by jackhump** [comment]
Dear Fei,

You can specify these contig junctions to be ignored during the clustering step by using the `--checkchrom` flag when you run leafcutter_cluster_regtools.py.

**Comment by feiyang555** [comment]
Hi Jack,


Thanks very much! I understand now:)


Best wishes,
Fei



发自我的iPhone


------------------ Original ------------------
