### ISSUE TITLE
Don't understand some lines of terminal output for leafcutter_ds.R 

### ISSUE THREAD

**Issue by feiyang555** [davidaknowles/leafcutter#130]
Hi all, 

It seems that I ran the leafcutter_ds.R successfully, but I got two errors in line 4 and 5 below.  Can anyone explain this to me? 

<img width="838" alt="Screen Shot 2020-03-16 at 7 41 15 pm" src="https://user-images.githubusercontent.com/59793400/76755069-32af0700-67be-11ea-99bd-524084bbef29.png">
many thanks, 
Fei

**Comment by goldenflaw** [comment]
Hi Fei,

I don't think you need to work about this, it seems that most of your tests
are successful?

Best,
Yang

**Comment by feiyang555** [comment]
Dear Yang,&nbsp;


Thanks very much, you are right, most of the tests are successful:)


Cheers,&nbsp;
Fei&nbsp;



发自我的iPhone


------------------ Original ------------------
