### ISSUE TITLE
No significant clusters found, but many differentially excised intron found with deltaPSI > 0.1 

### ISSUE THREAD

**Issue by feiyang555** [davidaknowles/leafcutter#131]
Dear All,

I have came across an Error: No significant clusters found when preparing the RData file to visualise the results, then I added the -f 0.15 flag to this step, I can visualise the data successfully. Please see the screenshot below. But when I look at the leafcutter_ds_effect_sizes.txt, there are indeed so many differential excised introns with deltaPSI > 0.1 or < -0.1.  I am wondering why clusters including those introns didn't come out as significant clusters?   
# screenshot for shinyapp 
<img width="1021" alt="Screen Shot 2020-03-22 at 9 15 45 pm" src="https://user-images.githubusercontent.com/59793400/77250344-5ffa2a00-6c82-11ea-9d74-1129f598ce29.png">

# screenshot for leafcutter_ds_effect_sizes.txt
<img width="651" alt="Screen Shot 2020-03-22 at 9 20 04 pm" src="https://user-images.githubusercontent.com/59793400/77250436-f595b980-6c82-11ea-8f56-5948d207335b.png">

Could you please let me know what happened to my results? 
please have a look at my results file and scripts
<img width="962" alt="Screen Shot 2020-03-22 at 9 36 38 pm" src="https://user-images.githubusercontent.com/59793400/77250924-2d523080-6c86-11ea-985b-c5380dd3522c.png">

[leafcutter_ds_cluster_significance.txt](https://github.com/davidaknowles/leafcutter/files/4365305/leafcutter_ds_cluster_significance.txt)
[leafcutter_ds_effect_sizes.txt](https://github.com/davidaknowles/leafcutter/files/4365306/leafcutter_ds_effect_sizes.txt)
[groups_file.txt](https://github.com/davidaknowles/leafcutter/files/4365314/groups_file.txt)

Many thanks,

Fei

**Comment by jackhump** [comment]
Dear Fei,

I would point out that having a large deltaPSI does not always equate to a significant result. Looking at your effect sizes, only 67 out of 35,000 junctions have a dPSI > 0.1.  My hunch would be that the two groups are very heterogeneous and that may be masking any true effect.

However it is puzzling that you do not see any significant differences between your groups.  Do you have reason to believe that there would be splicing differences between the two groups? Do the two groups separate when you do a PCA of the junction counts or on the PCA of the junction ratios provided in the Shiny app?

Could there be technical or other confounding factors that you are not accounting for? You can  add covariates as extra columns in the groups file you use in the differential splicing step.  I would imagine you have a library preparation batches, RNA quality metrics like RIN. coverage metrics like % of reads mapping to mRNA bases etc that may be confounding your signal.

**Comment by feiyang555** [comment]
Dear Jack,

I checked my PCA plots in shiny app, case and control didn't separate. Please see the picture below. Now I am trying to include more covariates including (batch effects, library pool, age, etc) and will update to you very soon. 

On the other hand, could you please have a look at another issue # How to finalising the number of sQTLs https://github.com/davidaknowles/leafcutter/issues/133?   I am a little bit confused about   correction step, cause not sure how to deal with the fact that some introns of a cluster have same best SNP and different clusters may also have the same best SNP. I read the leafcutter paper, still don't understand what you mean by using Bonferroni correction  to control for the number of introns tested per cluster. Do you mean I need to write a specific R loop script to run Bonferroni correction for each cluster? In this case, how to the different cluster may also have the best same SNP? 

Many thanks,

Fei 

<img width="879" alt="Screen Shot 2020-04-10 at 10 33 45 am" src="https://user-images.githubusercontent.com/59793400/78983697-43516380-7b57-11ea-8f63-2ca57a38617f.png">

**Comment by jackhump** [comment]
The variance explained is also very low for the first 2 PCs, which is odd. I'm suspicious about your data. Have you run PCA on normalised gene expression values? Do you see a similar lack of clustering?

**Comment by feiyang555** [comment]
Dear Jack,

Thanks very much for your reminding. I I am looking for this part of results now cause I didn't do this part and will let you know later. From what I know, there is no significantly differentially expressed genes after Benjamini-Hochberg correction between two groups. If the analysis process is correct, I guess another potential reason might be that there is no too much differences between two groups, right? 

Best regards,

Fei

**Comment by jackhump** [comment]
I see. Yes, I would be surprised to find differential splicing between two groups that didn't have any differential expressoin.
