### ISSUE TITLE
Hard-clipped bases not accounted for

### ISSUE THREAD

**Issue by kmcoyle** [davidaknowles/leafcutter#132]
I had been running bam2junc.sh and only getting outputs on chr1. Through further troubleshooting, I (& colleagues) identified that the STAR default to allow hard-clipping was resulting in unanticipated H characters in the cigar strings. The sam2bed.pl (line 101) is throwing an error (Broken pipe).

Replacing the "S" with [HS] in the CIGAR string as below seemed to solve the issue.

```
#remove soft cliped nucleotides
        if ($CIGAR =~/^\d+[HS](.*?)$/)
        {
                $CIGAR = $1;
        }
        elsif ($CIGAR =~/^(.*?)\d+[HS]$/)
        {
                $CIGAR = $1;
        }
```

Alternatively, specifying in the documentation that STAR should be run with `--chimOutType WithinBam SoftClip` would also help others bypass this.

**Comment by jackhump** [comment]
bam2junc.sh has now been replaced by regtools for junction extraction.
