### ISSUE TITLE
how to finalise sQTL number after fastQTL analysis

### ISSUE THREAD

**Issue by feiyang555** [davidaknowles/leafcutter#133]
Dear All,

Can I ask a question about how to finalise the number of sQTLs found by leafcutter and FastQTL ?  A little bit confused after read the paper and didn't find similar questions online.

I have attached the screenshot for the part of my FastQTL results,  different introns within the same or different cluster may have same best SNP. 
<img width="789" alt="fastQTL results" src="https://user-images.githubusercontent.com/59793400/78984541-17cf7880-7b59-11ea-8f87-cbd8e525a59a.png">

From the leafcutter paper (please see attached screenshot),  after got the corrected p-value from fastQTL, the Bonferroni correction was used to control for the number of introns tested per cluster, then the Benjamini-Hochberg was used to estimate the FDR.  My understanding is  that I need to write a specific R loop script to apply Bonferroni correction for every cluster to control the intron numbers, right?  Then I should apply the Benjamini-Hochberg to all introns in one step ( d$bh = p.adjust(d$bpval, method="fdr"), right?
<img width="685" alt="leafcutter-highlighted part" src="https://user-images.githubusercontent.com/59793400/78984560-261d9480-7b59-11ea-98d5-d81e37d149b7.png">

Many thanks,

Fei

**Comment by jackhump** [comment]
Dear Fei, I suggest you read up on the permutation analyses that FastQTL can do: http://fastqtl.sourceforge.net/ 

Personally, I use QTLtools instead of fastQTL as it allows you to group phenotypes in the permutation step. I group Leafcutter clusters by gene so that the permutation step outputs the most significant cluster per gene. That's what GTEX do as well.

**Comment by feiyang555** [comment]
Dear Jack,

The result I showed you is from the FastQTL permutation analysis but I didn't add the --grp option in FastQTL.  I suppose I should add this flag as well. But from the leafcutter paper screenshot above, there is another step - Bonferroni correction to control the number of introns per cluster. What is this step? How to achieve this step? Do you suggest this step as well? 

Many thanks,
Fei

**Comment by jackhump** [comment]
I didn't perform those analyses so I can't advise. Yang or David may see this and be able to answer.

**Comment by feiyang555** [comment]
I see :) Thanks very much Jack, &nbsp;I will add the flag and try FastQTL again as well as the QTLtools .&nbsp;And, could you please help tag them? &nbsp; Very looking forward to the response&nbsp;


Best regards,&nbsp;
Fei



发自我的iPhone


------------------ Original ------------------

**Comment by feiyang555** [comment]
Hi all, 

So grateful to get answer from another leafcutter developer Yang, and wanted to posted it here in case anyone needs it in the future. 

Because the number of sQTLs is counted as the number of clusters with a significant intron, and thus they generally take the minimum p-value of all introns for each cluster, they also correct for multiple testing (by multiplying the number of introns to the min p-value for each cluster). Plus, they didn't use --grp in FastQTL. 

Many thanks,

Fei

**Comment by feiyang555** [comment]
Dear Jack, 

Hope you are well at this stage. 

Could you please let me know how do you group the leafcutter clusters by gene ?   I have searched online and looked the gtf file and our leafcutter phenotype bed file,  but couldn’t get any idea. It is a bit hard for me to do this,  could you please give me some hints? 

Many thanks,

Fei

**Comment by jackhump** [comment]
Dear Fei, 

I suggest you look at the pipeline that the GTEX consortium uses: https://github.com/broadinstitute/gtex-pipeline/tree/master/qtl

Unfortunately they do not document the splicing QTL part of the pipeline in much detail but it involves running the cluster_prepare_fastqtl.py script, which itself incorporates Leafcutter scripts for junction clustering and preparing the phenotype table.

For grouping the junctions by gene you can use QTLtools or tensorQTL, either of them can perform the permutation testing by group (in this case gene).

**Comment by feiyang555** [comment]
Dear Jack,

Thanks so much for your explanation.  After read the description of performing the permutation testing by group in QTLtools, it didn't give the detail about how to prepare the phenotype bed file containing the grouped gene. I mean, the leafcutter only output the intron phenotype, how to map those intron to the right gene? I am confused in this step. I am not sure whether it is a stupid question, I indeed have no idea and couldn't find out the answer online. Could you please give me some hints or key R function or package? 

Many thanks,

Fei

**Comment by jackhump** [comment]
Please read through the cluster_prepare_fastqtl.py script in the GTEx repo.

**Comment by feiyang555** [comment]
Thanks very much Jack, I will have a quick try now. 

BW

Fei
