### ISSUE TITLE
Which intron is differentially spliced ?

### ISSUE THREAD

**Issue by gouthamatla** [davidaknowles/leafcutter#134]
Hi All,

Leafcutter reports the cluster name that is differentially spliced but I would like to know which intron is differentially spliced ? I know that its complimentary in simple splicing events that if one junction goes up, the other junction should go down. I would like to know if there is any way to retrieve the junction in complex splicing event.

```
cluster	status	loglr	df	p	p.adjust	genes
chr2:clu_450_NA Success 89.2146532318011        27      2.92785825943659e-24    8.21820534841257e-20    AC006369.1
chr1:clu_5221_NA        Success 70.8601148615003        13      9.51440737154487e-24    1.33529950255946e-19    FLAD1
chr11:clu_12004_NA      Success 58.1080415030156        6       1.01481213659974e-22    9.49492062073937e-19    FXYD6-FXYD2,FXYD2

```

Thanks,
Goutham A

**Comment by goldenflaw** [comment]
As you described, one intron can not change on its own, it must be
accompanied by changes at other introns. That being said, you can
certainly use the intron with the smallest p-value and/or largest
delta PSI estimated as the focal intron.

Best,
Yang

**Comment by jackhump** [comment]
It's usually easiest to visualise these complex events using LeafViz. For each cluster the junctions are labelled alphabetically by the largest delta PSI so junction A should have the largest change between groups.

**Comment by gouthamatla** [comment]
Okay. Thanks for quick reply.
