### ISSUE TITLE
prepare_phenotype_table discrepancy input

### ISSUE THREAD

**Issue by lindsay-liang** [davidaknowles/leafcutter#138]
Hi team,

I'm trying to run prepare_phenotype_table.py on my perind_numers.counts.gz file generated by leafcutter.  The file looks like this, consistent with the documentation.

HSB194 HSB615 HSB501 HSB411 HSB496 HSB107 HSB494 HSB674 
chr22_KI270876v1_alt:102741:130778:clu_1_NA 0 0 0 2 0 1 0 0 
chr22_KI270876v1_alt:102744:130778:clu_1_NA 0 0 1 0 0 0 0 1

However, there are two problems I'm seeing when running prepare_phenotype_table.py right now:
1) The line `chrom = dic['chrom'].replace("chr",'')` expects there to be a 'chrom' field in the header/sample line; there is no such field generated by clustering/leafcutter_cluster.py, or in the example perind_numers.counts.gz in the documentation.
2) The line `num, denom = count.split('/')` expects there to be two values, separated by `/` for each cluster, for each sample in the table.  There is only one value present in both my data and the example perind_numers.counts.gz in the documentation.

Have I run an out of date version of the code? Is there a quick fix I can do to prepare_phenotype_table.py to get around these dependencies? 

Thanks.

**Comment by jackhump** [comment]
Hi Lindsay,

I've had success with using the GTEX pipeline for splicing QTLs which makes use of Leafcutter clustering. The repo is here: https://github.com/broadinstitute/gtex-pipeline
and the important script is here: https://github.com/broadinstitute/gtex-pipeline/blob/master/qtl/leafcutter/src/cluster_prepare_fastqtl.py

@goldenflaw may be able to advise

**Comment by goldenflaw** [comment]
You should not use numers as the input, but the other file output by
clustering.

Best,
Yang
