### ISSUE TITLE
A bug in filter_cs.py 

### ISSUE THREAD

**Issue by boxiangliu** [davidaknowles/leafcutter#143]
Hello David and Yang, 

Hope you are doing well! 

In filter_cs.py, line 19 `edge5, edge3 = cs_split_M[0], cs_split_M[-2].split("N")[-1]` will not be able to handle CIGAR strings like 22M361N36M1I16M. This is a real read from YRI individual NA18486. Currently, filter_cs.py can only handle simple CIGAR strings like 22M361N53M. 

Another case that the current filter_cs.py cannot handle is  15M361N43M1I11M1357N5M, in which one read crosses two introns. 

I think regex is needed here to find two sides of N. 

Boxiang

**Comment by goldenflaw** [comment]
Hi Boxiang,

Filter_cs is deprecated, we now use regtools to extract junctions.

Best,
Yang

**Comment by boxiangliu** [comment]
Thank you!

See issue #127 

Closing this issue.
