### ISSUE TITLE
whether can Leafcutter Shiny App  support WSL

### ISSUE THREAD

**Issue by DerekTerry** [davidaknowles/leafcutter#147]
How can I  visualize on  WSL to call the chrome.exe ( installed in windows system) ?

Typing:
```
./run_leafviz.R   ./leafcutter_AS/AB_AS/leafviz.RData
```
get the following result:

```
Listening on http://127.0.0.1:3768
Error in utils::browseURL(appUrl) :
  'browser' must be a non-empty character string
Calls: <Anonymous> -> <Anonymous>
Execution halted
```

**Comment by phil-obrien** [comment]
Hi Derek,

I was getting the same error when running the same script, but I was using Ubuntu 20.04 (a Linux distribution).

I modified the script as follows (new code marked with philob begin and end). The code around the "philob" marks is existing code in the script (I've included it so you can see where to put the new code).

The new code goes in close to the bottom of the script. It's a slightly unsatisfactory fix in the sense that really it should look for the default browser and use that - but as long as you have Chrome installed, then hopefully the same fix will work on your Windows system too.

Let me know if it fixes your issue :-)

cheers, Phil

print(paste0("Loading results from ",results_filename))
load(results_filename)

# philob begin
if (getOption("browser") == ""){
  print("philob: setting browser option to firefox")
  options(browser = "firefox")
}
# philob end

shiny::runApp( launch.browser=TRUE )

**Comment by jackhump** [comment]
Hi @phil-obrien  and @DerekTerry , thanks for pointing this out. I've made a PR to add this: #156
