### ISSUE TITLE
Problem with ds_plots.R 

### ISSUE THREAD

**Issue by DerekTerry** [davidaknowles/leafcutter#148]
without symbol and loci info annotation

```
./ds_plots.R -e ../ovis_aries_exons.txt ../HYayImus_perind_numers.counts.gz \
../leafcut_groupAB.txt leafcutter_ds_cluster_significance.txt -f 0.05
```

![image](https://user-images.githubusercontent.com/54352433/88458553-7bd83b80-cec1-11ea-9028-85eb4996eae6.png)

**Comment by UMKG** [comment]
I was getting the same problem.
I guess Intron usage counts file is missing,,,but I can't fix it.

**Comment by jackhump** [comment]
Hi both,

ds_plots.R is now deprecated in favour of the LeafViz shiny app for visualising clusters.

**Comment by UMKG** [comment]
Dear jackhump.

Thank you for your comment!
Okay, I got it.

UMKG


2020年9月26日(土) 0:02 Jack Humphrey <notifications@github.com>:
