### ISSUE TITLE
Do not complete the demo data running

### ISSUE THREAD

**Issue by UMKG** [davidaknowles/leafcutter#152]
Hi,
When performing the demo set, I've encounterd 
freezing the "worked_example.sh" program, maybe, during the section of the preparation for visualisation by ./run_leafviz.R.
Annotation was finished and ds_plots.pdf was obtained.
Also, I found the result on the shiny app., but "./worked_example.sh" did not complete.

Here is the summary of the session log:
```
$./worked_example.sh
,
,
,
,
[1] "Annotating junctions"
[1] "Preparing results"
[1] "converting counts to ratios"
`mutate_all()` ignored the following grouping variables:
Column `clu`
Use `mutate_at(df, vars(-group_cols()), myoperation)` to silence the message.
 警告メッセージ: 
`funs()` is deprecated as of dplyr 0.8.0.
Please use a list of either functions or lambdas: 
  # Simple named list: 
  list(mean = mean, median = median)
  # Auto named with `tibble::lst()`: 
  tibble::lst(mean, median)
  # Using lambdas
  list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
[1] "creating PCA",
,
,
,
,
[1] "Loading results from testYRIvsEU.RData"
Listening on http://127.0.0.1:5801
,
,
,
<----freeze point
```

I'm ruuning macOS Catalina on Mac Pro(Late 2013)
CPU: 3 GHz 8 cores Intel Xeon E5
Memory: 128 GB 1066 MHz DDR3

Any suggestions?

Thank you in advance for your help.

**Comment by jackhump** [comment]
Dear UMKG,

Are you saying that the shiny app loaded up on your browser? If so, then yes the code is supposed to freeze as it's running the app.

If the shiny app didn't start on your browser then there's a problem.

**Comment by UMKG** [comment]
Dear jackhump.

Thank you for your comment!
The Shiny app was loaded successfully and I was able to see it in my browser.
I understand that my previous comment was a normal run, so I'm going to close the section.

Thank you for your continued support.
