### ISSUE TITLE
leafcutter_cluster.py is not working on the new file format of .junc

### ISSUE THREAD

**Issue by shannjiang** [davidaknowles/leafcutter#163]
Hi,

I am trying to do intron clustering with leafcutter_cluster.py on the .junc files generated.

I found the python script is working fine on the old .junc file format like this:
![old_leafcutter_res](https://user-images.githubusercontent.com/31867080/95896212-80d6b980-0d51-11eb-853b-2485babbcf2b.png)
But got error when on the new .junc file format like this:
![new_leafcutter_res](https://user-images.githubusercontent.com/31867080/95896276-a06de200-0d51-11eb-8c06-30d35e0c75fc.png)
Error info:
[jiangs09@li03c03 leafcutter]$ python /sc/arion/projects/CommonMind/roussp01a/alz_phg_bin_zhang/rnaseq/leafcutter/clustering/leafcutter_cluster.py -j /sc/arion/projects/CommonMind/roussp01a/alz_phg_bin_zhang/rnaseq/temp/leafcutter.list.txt -m 50 -o PHG -l 500000
scanning /sc/arion/projects/CommonMind/roussp01a/alz_phg_bin_zhang/rnaseq/batch//Sample_178941-MgAs-RNA/Processed/RAPiD/leafcutter/Sample_178941-MgAs-RNA.reverse.output.junc...
Traceback (most recent call last):
  File "/sc/arion/projects/CommonMind/roussp01a/alz_phg_bin_zhang/rnaseq/leafcutter/clustering/leafcutter_cluster.py", line 489, in <module>
    main(options, libl)
  File "/sc/arion/projects/CommonMind/roussp01a/alz_phg_bin_zhang/rnaseq/leafcutter/clustering/leafcutter_cluster.py", line 11, in main
    pool_junc_reads(libl, options)
  File "/sc/arion/projects/CommonMind/roussp01a/alz_phg_bin_zhang/rnaseq/leafcutter/clustering/leafcutter_cluster.py", line 46, in pool_junc_reads
    chrom, A, B, dot, counts, strand = lnsplit
ValueError: too many values to unpack

the old format is generated with leafcutter 0.2.7 which is the last release in 2017, and the new format is generated with the version from Github at 2019/09/10, commit 54235a4.
Is there a new leafcutter_cluster.py script I can use on the new format or I have to convert the new .junc back to the old one? I guess there are more information in the new format, right?

thanks,

Shan

**Comment by jackhump** [comment]
Dear Shan,

hello to a fellow Sinai person!  

The 'new' junction format is created by regtools. To perform clustering you must use leafcutter_cluster_regtools.py script.

Users have reported issues with using leafcutter_cluster_regtools.py . This can either be due to chromosome naming (use the --checkchrom flag to throw out any non-standard chromosomes) or "?" in the stranding, which is due to the -s parameter in regtools not matching the stranding of your library.

best wishes,

Jack

**Comment by shannjiang** [comment]
Dear Jack,

The new python script is working on the new format!

Thanks! Just noticed you are also from Sinai, lol. You are smart can locate me thru the path info, lol.

Shan
