### ISSUE TITLE
wrangle annotation output for gencode_hg38

### ISSUE THREAD

**Issue by hothri** [davidaknowles/leafcutter#165]
Hi, 
I have noticed that gencode_hg38 annotations are not properly written out. 
In gencode_hg38_all_exons.txt column gene_name have gene type values rather than gene_name
I am pasting few lines from the .txt file for your reference. 

> chr start end strand gene_name
chr1 11869 12227 + processed_transcript
chr1 12613 12721 + processed_transcript
chr1 13221 14409 + processed_transcript
chr1 12010 12057 + transcribed_unprocessed_pseudogene
chr1 12179 12227 + transcribed_unprocessed_pseudogene
chr1 12613 12697 + transcribed_unprocessed_pseudogene
chr1 12975 13052 + transcribed_unprocessed_pseudogene
chr1 13221 13374 + transcribed_unprocessed_pseudogene
chr1 13453 13670 + transcribed_unprocessed_pseudogene

Thank you, 
Hothri

**Comment by jackhump** [comment]
Hi Hothri,

this is a known issue. Please make your own GENCODE hg38 annotation using our gtf2leafcutter perl script.

**Comment by jackhump** [comment]
@davidaknowles  can I send you  fixed versions of the hg38 files to maintain?

**Comment by hothri** [comment]
The error is after using wrangle_annotation.sh for creating annotations.

**Comment by jackhump** [comment]
wrangle_annotation.sh is no longer recommended. We switched to gtf2leafcutter.pl

**Comment by hothri** [comment]
Thanks it worked
