### ISSUE TITLE
Missing R package pre-reqs

### ISSUE THREAD

**Issue by rdocking** [davidaknowles/leafcutter#17]
Hi there - I was attempting to run through the `worked_out_example.sh` script, and encountered a few hang-ups. It looks like the `optparse` and `doMC` packages were not installed along with LeafCutter when installing the package via devtools. Installing the packages manually did the trick though.

**Comment by davidaknowles** [comment]
Thanks for pointing this out! I've added those dependencies to `DESCRIPTION` so they should get installed by `devtools` now.

**Comment by rdocking** [comment]
Great - thanks!
