### ISSUE TITLE
continuous independent variables

### ISSUE THREAD

**Issue by zhangguy** [davidaknowles/leafcutter#175]
Thanks for developing this amazing package.

I got some RNAseq data with a continuous (numeric) variable, like severity of disease. Is there a way to run the data in leafcutter without converting to categorical?

Thanks!

**Comment by jackhump** [comment]
Leafcutter's differential splicing test only supports a case control group design.

You could instead take the output of the clustering step and correlate each junction proportion with your variable of interest. I believe something like this was done by Gandal et al in their Science paper on the PsyChENCODE consortium data.
