### ISSUE TITLE
Calculation of PSI

### ISSUE THREAD

**Issue by rdocking** [davidaknowles/leafcutter#18]
Hi there,

  I've been playing with LeafCutter, and going through the code and manuscript, I can't quite figure out how the PSI values are calculated. For example, in Figure 2a in the manuscript, I can't quite figure out how the PSI values were calculated for the clustering. 

  I've been able to run through the example data set, and have loaded all the count data into R. Is there some function included in the package for converting the count data to PSI, or is that calculated elsewhere? Thanks!

**Comment by goldenflaw** [comment]
The PSIs for LeafCutter are not the standard PSIs, you can simply take the
numerical value (ratio) for one intron in each cluster as "PSI" (you want
to take one that show some variation across your samples).

Best,
Yang

**Comment by rdocking** [comment]
Hi Yang - thanks for your response! I think I've figured out how to calculate PSI as you suggest. You can close this issue.
