### ISSUE TITLE
documentation alert/update: regtools extract is bed12

### ISSUE THREAD

**Issue by bfairkun** [davidaknowles/leafcutter#180]
In the converting bams to juncs step of the differential splicing section of the online documentation, you suggest using regtools extract:

```
regtools junctions extract -a 8 -m 50 -M 500000 $bamfile -o $bamfile.junc
```

I am using regtools 0.5.2, and in my version (not sure if this applies to previous versions) the output of this command is bed12 format that should match the format of the junctions.bed output from TopHat. See the [regtools documentation](https://regtools.readthedocs.io/en/latest/commands/junctions-extract/). This means that the Start and Stop fields do not correspond to the start and stop of introns. I don't think this will mess up clustering, so this isn't a bug per se. But it might mess people up if they are trying to parse the clustering (or differential splicing) output for annotated introns based on coordinates. I suggest fixing this by using this awk snippet to fix the start and stop to correspond to the start and stop of introns:

```
regtools junctions extract -a 8 -m 50 -M 500000 $bamfile | awk -F'\t' -v OFS='\t' '{split($11, blockSizes, ","); print $1,$2+blockSizes[1],$3-blockSizes[2],$4,$5,$6}' > $bamfile.junc
```

Best,
Ben

**Comment by Zepeng-Mu** [comment]
I fell like this is adjusted in the clustering step. So changing it in junction file would mean changing the code for clustering step as well.

https://github.com/davidaknowles/leafcutter/blob/3f875f1ac05a0f0413884c0d016b3c7ae17713c9/scripts/leafcutter_cluster_regtools.py#L54-L55

Maybe it's easier to get introns from leafcutter intron names generated by the clustering step. Hopefully this satisfies your needs for annotating introns.

**Comment by bfairkun** [comment]
Good point @Zepeng-Mu. This "bug" just popped up for me because I have been used to using the old clustering script with junctions files in bed6 format with intron start and intron stop in fields 2 and 3. I now see that using leafcutter_cluster_regtools.py fixes this if you use the BED12 format junctions files.  I'll close the issue.
