### ISSUE TITLE
Differential Splicing: intron clustering

### ISSUE THREAD

**Issue by chanalim** [davidaknowles/leafcutter#187]
Hi, I am following the walkthrough document on leafcutter and I have so far created all the junction files for all of my samples. I also did intron clustering on those samples, however, I do not plan to use all of the samples in the Differential intron excision part of the analysis. Do I need to rerun intron clustering with only the samples that will used?

**Comment by goldenflaw** [comment]
No, you don't. You can use the perind file.

Best,
Yang

**Comment by chanalim** [comment]
@goldenflaw Awesome!, thank you so much for the quick respond. Have a wonderful day!
