### ISSUE TITLE
BUG report: cluster_ensemblID == "." should be cluster_ensemblID <- "." in line 201 of prepare_results.R

### ISSUE THREAD

**Issue by wong-ziyi** [davidaknowles/leafcutter#199]
error message if `cluster_ensemblID == "."`  in line 201 of prepare_results.R :
```
Error: Problem with `mutate()` column `ensemblID`.
ℹ `ensemblID = ifelse(is.na(ensemblID), ".", ensemblID)`.
ℹ `ensemblID` must be size 24 or 1, not 0.
Backtrace:
  █
1. ├─`%<>%`(...)
2. ├─dplyr::mutate(...)
3. ├─dplyr:::mutate.data.frame(...)
4. │ └─dplyr:::mutate_cols(.data, ..., caller_env = caller_env())
5. │   ├─base::withCallingHandlers(...)
6. │   └─mask$eval_all_mutate(quo)
7. └─dplyr:::abort_glue(character(0), list(x_size = 0L), "dplyr:::mutate_incompatible_size")
8.   └─rlang::exec(abort, class = class, !!!data)
Execution halted
```

**Comment by abhilashdasari** [comment]
I am also facing the same issue.
Any solution?

**Comment by jackhump** [comment]
which version of R are you using? I don't see that error when running prepare_results.R

**Comment by abhilashdasari** [comment]
I am using `R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"`

**Comment by jackhump** [comment]
can you try changing line 201 to 

```
cluster_ensemblID <- "."
```

and report back if that fixes the issue? I can make a pull request for it.

**Comment by abhilashdasari** [comment]
It worked.
Thanks a lot.
I have created a pull request.

Along with that, I wrote a small description of this error.  
Correct it if anything is wrong.

**Comment by wong-ziyi** [comment]
Thanks so much for everybody. Since this error has been fixed, I closed this issue.
