### ISSUE TITLE
Possible bug in clustering approach

### ISSUE THREAD

**Issue by birndle** [davidaknowles/leafcutter#2]
Hello,

After reading through the leafcutter_cluster.py code, I've noticed that there may be edge cases where introns are not clustered properly. Specifically, I mean that some of the final clusters (after the refine_clusters step has been run) may not actually form well-connected graphs as described in the paper.

For example, suppose you have three overlapping introns with coordinates (1, 10), (5, 10), and (5, 20), with respective read counts of 10, 5, 10. Cluster_intervals will group these introns together since they overlap. Then, refine_linked will connect this cluster of overlapping introns into a graph since (1, 10) and (5,10) share an edge and (5,10) and (5, 20) also share an edge. 

However, during the refine_cluster step, the (5, 10) intron will be purged since it has a read count < 10. Then you are left with two introns: (1, 10) and (5, 20). These will be re-clustered together at line 367 since they still overlap. Refine_cluster will proceed to then return this cluster to the parent function refine_clusters where it will be written to output as a "refined cluster". However, **despite overlapping, these two introns do not share an acceptor or a donor site** and thus shouldn't form a "refined_cluster". 

I believe this behavior is inconsistent with the description of the method in the paper. But, please let me know if I am misinterpreting something. Hope this is helpful.

Regards,
Dan

**Comment by goldenflaw** [comment]
Thanks Dan,

We'll check this out. Might take a bit longer than usual as I'm traveling over the next few weeks.

Cheers,
Yang

**Comment by birndle** [comment]
Thanks for the response, Yang. Looking forward to hearing more.

**Comment by goldenflaw** [comment]
Sorry for the delay, should be fixed.

**Comment by birndle** [comment]
Great, thanks!
