### ISSUE TITLE
'Rcpp::loadRcppModules' is deprecated.Use 'loadModule' instead.

### ISSUE THREAD

**Issue by aditi-2017** [davidaknowles/leafcutter#20]
Hello, 

Thank you for building this tool. I was running the working example and I keep getting a warning message about deprecated load used for Rcpp.  Please see below :

merging 10 junction files...
merging 10 files done.
Loading required package: Rcpp
Warning messages:
1: replacing previous import ‘dplyr::filter’ by ‘stats::filter’ when loading ‘leafcutter’ 
2: replacing previous import ‘dplyr::lag’ by ‘stats::lag’ when loading ‘leafcutter’ 
3: 'Rcpp::loadRcppModules' is deprecated.
Use 'loadModule' instead.
See help("Deprecated") 
Loading counts from ../example_data/testYRIvsEU_perind_numers.counts.gz 
Loading metadata from ../example_data/test_diff_intron.txt 
Encoding as CEU =0, YRI =1
Loading required package: doMC
Loading required package: foreach
Loading required package: iterators
Loading required package: parallel
Settings:
$output_prefix
[1] "leafcutter_ds"

$max_cluster_size
[1] Inf

$min_samples_per_intron
[1] 5

$min_samples_per_group
[1] 3

$min_coverage
[1] 20

$timeout
[1] 30

$num_threads
[1] 4

$help
[1] FALSE

Running differential splicing analysis...
Differential splicing summary:
                                             statuses Freq
1                                             Success  523
2               <=1 sample with coverage>min_coverage    7
3                            Not enough valid samples   71
4 <2 introns used in >=min_samples_per_intron samples    1
Saving results...
No exon_file provided.
Warning message:
In bind_rows_(x, .id) : Unequal factor levels: coercing to character
All done, exiting
Loading required package: Rcpp
Warning messages:
1: replacing previous import ‘dplyr::filter’ by ‘stats::filter’ when loading ‘leafcutter’ 
2: replacing previous import ‘dplyr::lag’ by ‘stats::lag’ when loading ‘leafcutter’ 
3: 'Rcpp::loadRcppModules' is deprecated.
Use 'loadModule' instead.
See help("Deprecated") 
Loading counts from ../example_data/testYRIvsEU_perind_numers.counts.gz 
Loading metadata from ../example_data/test_diff_intron.txt 
Loading exons from ../leafcutter/data/gencode19_exons.txt.gz 
Saving 3 plots to ds_plots.pdf 
[1] "chr1:clu_11"
[1] CEU
Levels: CEU YRI

**Comment by davidaknowles** [comment]
This should be fixed now: please can you update and try installing again?
