### ISSUE TITLE
Redundant Splice Event Clustering

### ISSUE THREAD

**Issue by kfdowling** [davidaknowles/leafcutter#212]
Hello,

Thanks for putting together this great program. I've recently run into an error wherein multiple clusters appear to be identified for exactly the same splice events (e.g. start and end sites are identical for all the splice events in each of these two separate clusters, such that it seems only one cluster should have been generated). I've enclosed the graphics generated by leafviz to clarify the nature of this problem, where clu_5390_+_table.pdf and clu_5091_-_table.pdf are identified as separate clusters for the same splice event. 

[GRIN1_clu_5091_-_table.pdf](https://github.com/davidaknowles/leafcutter/files/8603998/GRIN1_clu_5091_-_table.pdf)
[GRIN1_clu_5390_+_table.pdf](https://github.com/davidaknowles/leafcutter/files/8603999/GRIN1_clu_5390_%2B_table.pdf)
![GRIN1_Dup_Splicing](https://user-images.githubusercontent.com/71798012/166263521-cb811219-4305-4c29-abaf-15bbc53de594.png)

Initially I applied -p 0.01 to the cluster regtools junction step and thought that could somehow cause the same splice event to be clustered into two different groups, but this issue occurs when I re-run the clustering using the default parameters for the -p option. 

For reference I am using the MMul10 ensembl .gtf and genome (Macaque) with about 15 samples per group, MacOSX 12.3.1, python 2.7, leafcutter 0.2.9 on R 4.1.2, and have had the same general issue with human data in prior analyses. I'm always inclined to assume an end user error over a bug, so I'd appreciate any advice advice you might have for further troubleshooting.

Thanks,
Kevin

Code used to generate data from .bam files: 

BAM_DIR=/Users/dowlingkf/Desktop/Supercomputer_Transfer_Repository/
Out_DIR=/Users/dowlingkf/Desktop/Supercomputer_Transfer_Repository/
for bamfile in `ls ${BAM_DIR}/*.bam`; do
    echo "Converting ${bamfile} to ${bamfile}.junc"
    samtools index $bamfile
    regtools junctions extract -s 1 -t XS -a 8 -m 50 -M 500000 -o ${Out_Dir}/$bamfile.junc $bamfile
    echo $bamfile.junc >> Primate_juncfiles_ensembl_non_merged.txt
done

python /Users/dowlingkf/leafcutter/scripts/leafcutter_cluster_regtools.py -j Primate_juncfiles_ensembl_non_merged.txt -m 50 -l 500000 -o MiddlePrimate_m50 -l 500000

/Users/dowlingkf/leafcutter/scripts/leafcutter_ds.R -e /Volumes/Extension/Primate_Ipsi_Cont_18_46mo_RNAseq/ENSEMBL_BAM_FILES/Genome_Files_Ensembl/Macaca_mulatta.Mmul_10.105_leafcutter_exons.gtf.gz --num_threads 8 /Users/dowlingkf/Desktop/Supercomputer_Transfer_Repository/MiddlePrimate_m50_p0_python2.7_perind_numers.counts.gz /Users/dowlingkf/Desktop/Matrix_File_Crude_Middle_Monkey_PFC_PPC.txt
 
/Users/dowlingkf/leafcutter/leafviz/prepare_results.R -o Crude_results_PFC_PPC_python2.7_p0.Rda -m ../Matrix_File_Crude_Middle_Monkey_PFC_PPC.txt -c Crude_PFC_PPC_p0_py2.7 MiddlePrimate_m50_p0_python2.7_perind_numers.counts.gz /Users/dowlingkf/Desktop/Supercomputer_Transfer_Repository/leafcutter_ds_cluster_significance.txt /Users/dowlingkf/Desktop/Supercomputer_Transfer_Repository/leafcutter_ds_effect_sizes.txt /Volumes/Extension/Primate_Ipsi_Cont_18_46mo_RNAseq/ENSEMBL_BAM_FILES/Genome_Files_Ensembl/MMul10_Ensembl_Leafcutter_Annotation

**Comment by kfdowling** [comment]
Hello,

Please disregard the above, the underlying driver of this behavior is how the strandedness was handled by the junction extraction step in regtools. Thanks again for the great package!

Best,
Kevin

**Comment by QuanlongJiang** [comment]
> Hello,
> 
> Please disregard the above, the underlying driver of this behavior is how the strandedness was handled by the junction extraction step in regtools. Thanks again for the great package!
> 
> Best, Kevin

Hi, I'm encountering the same issue. Could you please help me  how to handle this?

Thanks.
