### ISSUE TITLE
Error when using exon file 

### ISSUE THREAD

**Issue by asciae** [davidaknowles/leafcutter#22]
Hi, When I use the exon file with the example or my data, I get the following error:
Saving results...
Loading exons from /leafcutter/leafcutter/data/gencode19_exons.txt.gz 
Error in try({ : 
  unused argument (error = function(err) warning(as.character(err)))
Execution halted
----
I have tried changing the files to all use chr as well as removing chr from all files. Do you know what the problem could be?

**Comment by goldenflaw** [comment]
Have you tried to use the full path for your exon file?

Best,
Yang

**Comment by asciae** [comment]
Thank you Yang, I didn't copy the full path in my comment, but the path I am using exists (~/leafcutter/leafcutter/data/gencode19_exons.txt.gz)
Let me know if you would like any additional information!

**Comment by goldenflaw** [comment]
Could you try the full path without ~/, e.g. /home/yourusername/
leafcutter/leafcutter/data/gencode19_exons.txt.gz?

Yang

**Comment by asciae** [comment]
Thank you, I used the full path and still have the same error.
Best,
Ascia

**Comment by goldenflaw** [comment]
Could you paste a few lines from each of your input files here?

Thanks,
Yang

**Comment by asciae** [comment]
I am running this command for the example data:
 /home/aeskin/leafcutter/scripts/leafcutter_ds.R -e /home/aeskin/leafcutter/leafcutter/data/gencode19_exons.txt.gz /home/aeskin/leafcutter/example_data/testYRIvsEU_perind_numers.counts.gz /home/aeskin/leafcutter/example_data/test_diff_intron.txt 

/home/aeskin/leafcutter/leafcutter/data/gencode19_exons.txt.gz
chr start end strand gene_name
chr1 11869 12227 + DDX11L1
chr1 12613 12721 + DDX11L1
chr1 13221 14409 + DDX11L1
chr1 11872 12227 + DDX11L1

/home/aeskin/leafcutter/example_data/testYRIvsEU_perind_numers.counts.gz
RNA.NA06986_CEU.chr1.bam RNA.NA06994_CEU.chr1.bam RNA.NA18486_YRI.chr1.bam RNA.NA06985_CEU.chr1.bam RNA.NA18487_YRI.chr1.bam RNA.NA06989_CEU.chr1.bam RNA.NA06984_CEU.chr1.bam RNA.NA18488_YRI.chr1.bam RNA.NA18489_YRI.chr1.bam RNA.NA18498_YRI.chr1.bam
chr1:17055:17233:clu_1 21 13 18 20 17 12 11 8 15 25
chr1:17055:17606:clu_1 4 11 12 7 2 0 5 2 4 4
chr1:17368:17606:clu_1 127 132 128 55 93 90 68 43 112 137

/home/aeskin/leafcutter/example_data/test_diff_intron.txt 
RNA.NA18486_YRI.chr1.bam YRI
RNA.NA18487_YRI.chr1.bam YRI
RNA.NA18488_YRI.chr1.bam YRI
RNA.NA18489_YRI.chr1.bam YRI
RNA.NA18498_YRI.chr1.bam YRI
RNA.NA06984_CEU.chr1.bam CEU
RNA.NA06985_CEU.chr1.bam CEU
RNA.NA06986_CEU.chr1.bam CEU
RNA.NA06989_CEU.chr1.bam CEU
RNA.NA06994_CEU.chr1.bam CEU

gives me:
Running differential splicing analysis...
Differential splicing summary:
                                             statuses Freq
1                                             Success  523
2               <=1 sample with coverage>min_coverage    7
3                            Not enough valid samples   71
4 <2 introns used in >=min_samples_per_intron samples    1
Saving results...
Loading exons from /home/aeskin/leafcutter/leafcutter/data/gencode19_exons.txt.gz 
Error in try({ : 
  unused argument (error = function(err) warning(as.character(err)))
Execution halted

Thanks!

**Comment by goldenflaw** [comment]
I see, I usually run this command without the -e argument. Could you try
this so we can narrow down the error?

Thanks,
Yang

**Comment by asciae** [comment]
Thank you.
posting below:

Running differential splicing analysis...
Differential splicing summary:
                                             statuses Freq
1                                             Success  523
2               <=1 sample with coverage>min_coverage    7
3                            Not enough valid samples   71
4 <2 introns used in >=min_samples_per_intron samples    1
Saving results...
No exon_file provided.
Warning message:
In bind_rows_(x, .id) : Unequal factor levels: coercing to character
All done, exiting

**Comment by goldenflaw** [comment]
I'm guessing that this produced a non-empty output?

**Comment by asciae** [comment]
Yes, this is correct.

**Comment by mgandal** [comment]
I was getting the same error. I believe you need to use `tryCatch` instead of `try`

**Comment by davidaknowles** [comment]
I'll take a look at this now.

**Comment by davidaknowles** [comment]
Ok, should be fixed now. Thanks for pointing the issue out and let me know if you have any more problems!

**Comment by asciae** [comment]
Thanks so much!

**Comment by asciae** [comment]
Hi, could it be that this line is causing the path to be such:
args = strsplit( c("--num_threads 4 -e ../leafcutter/data/gencode19_exons.txt.gz ../example_data/testYRIvsEU_perind_numers.counts.gz ../example_data/test_diff_intron.txt"), " ")[[1]], 
   positional_arguments = 2)
I am getting errors. I don't have administrator privileges, so I am waiting for the software to be updated on our cluster. But this looks like it could be the error.
Even running -h for help I get:
/home/aeskin/leafcutter/scripts/leafcutter_ds.R -h
Loading required package: Rcpp
Warning messages:
1: replacing previous import by 'stats::filter' when loading 'leafcutter' 
2: replacing previous import by 'stats::lag' when loading 'leafcutter' 
3: 'Rcpp::loadRcppModules' is deprecated.
Use 'loadModule' instead.
See help("Deprecated") 
Loading counts from ../example_data/testYRIvsEU_perind_numers.counts.gz 
Error: File ../example_data/testYRIvsEU_perind_numers.counts.gz does not exist
Execution halted

Thanks!

**Comment by davidaknowles** [comment]
Ugh yes good spot. Fixed now!
By the way, you should be able to install without admin privileges, you can always install R packages to a local directory (i.e. somehow under your home directory on your cluster).

**Comment by asciae** [comment]
Thank you and thanks for the tip!
Sorry to be a pain! =)
But I am getting this error that I didn't get previously:
/home/aeskin/leafcutter/scripts/leafcutter_ds.R --num_threads 4 /home/aeskin/leafcutter/example_data/testYRIvsEU_perind_numers.counts.gz /home/aeskin/leafcutter/example_data/test_diff_intron.txt

Running differential splicing analysis...
Error in differential_splicing(counts, numeric_x, confounders = confounders,  : 
  unused argument (confounders = confounders)
Execution halted

Thanks again!

**Comment by davidaknowles** [comment]
I think this is because you have the new leafcutter_ds.R script but the package hasn't been reinstalled yet. Can you try installing the package locally - I think you just need to do e.g.
`install_github("davidaknowles/leafcutter/leafcutter", lib="~/myRlibs/")`
or wherever in your home dir you want to put personal packages.

**Comment by asciae** [comment]
Thanks so much, it works, and with the annotation!
