### ISSUE TITLE
Intron Clustering

### ISSUE THREAD

**Issue by JaydenBeckwith** [davidaknowles/leafcutter#233]
Hi, 

I'm just having some trouble getting intron clustering to work. I have followed the documentation as per instructions and have the junction files for my samples.

![image](https://user-images.githubusercontent.com/55827127/232360818-26daee2d-19fa-4d36-98c0-5e2cd8107876.png)

However, when I zcat the counts per individual there is no counts per cluster? I have used the default clustering parameters and also have tried other parameters.

Thanks

**Comment by jackhump** [comment]
Hi! Can you show us the command you used and the error messages generated while clustering?

**Comment by JaydenBeckwith** [comment]
Hi Jack, 

Here are the commands I used, no errors per se (just nothing is clustered in the output) :

for bamfile in *bam; do regtools junctions extract -s 0 -a 1 -m 50 -M 500000 $bamfile -o $bamfile.junc; done

for bamfile in *bam;
echo $bamfile.junc >> test_juncfiles.txt; done 

#clustering counts 
python leafcutter_cluster_regtools.py -j test_juncfiles.txt -m 1 -o clusteranalysis -l 500000

zcat clusteranalysis_perind_numers.counts.gz | more

**Comment by jackhump** [comment]
and just to check, you do have junctions in each file? that's the only thing I could think of that would cause an empty cluster output.

Also, you're using python 3 right? We updated all the scripts in the last year or so.

**Comment by JaydenBeckwith** [comment]
Hi Jack,

That makes more sense - I think I was using python 2.7. Hence why it was probably not working!

Thanks for your help :)

**Comment by Dongmeng-wang** [comment]
Hello, I used the latest code for clustering amd also got 0 cluster without any errors. I used python 3.9. Did you fix this problem in your case? Thanks.

**Comment by Joyjoyjoyc** [comment]
> Hi Jack,
> 
> Definitely have junction files - screenshot of one of my samples
> 
> ![image](https://user-images.githubusercontent.com/55827127/235831990-c08d69b1-d59d-4fb8-ad73-5516a7860d41.png)
> 
> That makes more sense - I think I was using python 2.7. I'll check to see if that's the issue
> 
> Thanks for your help :)

Hi, @JaydenBeckwith 
I got the same question as you, and my python version is 3.7. My output of .junc files also look the same as yours. I wonder did you figure it out? Thank you so much!

**Comment by Joyjoyjoyc** [comment]
> Hello, I used the latest code for clustering amd also got 0 cluster without any errors. I used python 3.9. Did you fix this problem in your case? Thanks.

Hi, did you figure it out? my python version is 3.7. Thanks!

**Comment by QuanlongJiang** [comment]
I got same problem. did you solve it?
