### ISSUE TITLE
an error about leafcutter_cluster.py

### ISSUE THREAD

**Issue by Fight-a-tiger-in-the-mountain** [davidaknowles/leafcutter#237]
After I use bam2junc.sh to convert the bam file to a file without a suffix (should be junction) file, I run it with leafcutter_cluster.py, but with "Error: no junction file provided... "

$leafcutter_cluster.py SRR8280689.junction 
Error: no junction file provided...

The input path is correct and the file exists. (Previous step bam2junc.sh) No error is reported,What's the problem, please

**Comment by jackhump** [comment]
we are no longer supporting bam2junc.sh, please use regtools for junction extraction.

**Comment by xuxunan** [comment]
I ues regtools but always get 
ValueError: not enough values to unpack (expected 12, got 6)
What can I do with this problem, please

**Comment by Fight-a-tiger-in-the-mountain** [comment]
收到

**Comment by jackhump** [comment]
we've deprecated leafcutter_cluster.py, please use leafcutter_cluster_regtools.py
