### ISSUE TITLE
feature request: strand in perind.counts

### ISSUE THREAD

**Issue by isthisthat** [davidaknowles/leafcutter#24]
It would be great to keep the strand information in the clustered junction output. It is very hard to get post-hoc. Or can you suggest an alternative?
Thanks a lot.

**Comment by goldenflaw** [comment]
Agreed, I have a version that we're trying to roll in. But as you know
we're all quite busy :). Can you shoot David and I a personal e-mail?

Best,
Yang

**Comment by goldenflaw** [comment]
We have added a new script leafcutter_cluster_regtools.py which have strands added>
