### ISSUE TITLE
leafviz visualization does not show gene names

### ISSUE THREAD

**Issue by XuBian** [davidaknowles/leafcutter#244]
after differential splicing step, I got 285 success in summary. Yet few genes showed gene names, as for the subsequent leafviz visualization, only "LINC00293" showed in "Gene", other results did not show gene names.
![图片1](https://github.com/davidaknowles/leafcutter/assets/129267395/9276aaae-a237-455e-bb2e-feea80c29cf4)

**Comment by jackhump** [comment]
Hi, this is likely an issue with the gene annotations you are using. Try regenerating them from the same GTF you use in the alignment using gtf2leafcutter.pl
