### ISSUE TITLE
--outSAMtype BAM Unsorted ?

### ISSUE THREAD

**Issue by ls233** [davidaknowles/leafcutter#249]
Great tool, congrats!

Question, if I produce unsorted BAM files (--outSAMtype BAM Unsorted), the SAMTOOLS will fail indexing it. 

Should I possibly run STAR with "--outSAMtype BAM SortedByCoordinate" ?

**Comment by jackhump** [comment]
yes, BAM files must be coordinate sorted for indexing to work, and subsequently regtools junction extraction.

**Comment by ls233** [comment]
So do you recommend having STAR producing a sorted BAM or having STAR
producing an unsorted BAM and sorting it thereafter before indexing?

**Comment by jackhump** [comment]
I would use STAR to output a coordinate-sorted BAM. If you've already done the alignment then you could just sort them using Samtools.
