### ISSUE TITLE
Scaffolded genomes update?

### ISSUE THREAD

**Issue by harpur** [davidaknowles/leafcutter#25]
Great software, thanks. I had a quick suggestion.  If software is designed to be annotation free, it would be nice to use it on genomes other than human. Would be good to change this line in `leafcutter_cluster.py` to account for non-human chromosome numbers, and scaffolded genomes:

` chromLst = ["chr%d"%x for x in range(1,23)]+['chrX','chrY', ]+["%d"%x for x in range(1,23)]+['X','Y'] 
`    

EDIT: strike that--I see you've got lines accounting for chroms not in chromLst

**Comment by shoersch** [comment]
Re-opened as #42 , still very relevant.

**Comment by pengchy** [comment]
Dear LeafCutter developers,

Could you help update the leafcutter_cluster_regtools.py to accept the genome other than human? I found this script is very useful to cluster junctions, but it turned out to only work for human genome.
Best,
