### ISSUE TITLE
run_leafviz.R error

### ISSUE THREAD

**Issue by Yang-Yingshan** [davidaknowles/leafcutter#260]
Hi!
This is the problem I encountered when using the leafcutter software, I sincerely ask you for advice, and I hope to have a reply
Warning: Error in make_cluster_plot: object 'gene_name_df' not found
  171: make_cluster_plot
  167: renderPlot [/public/home/yangjie/yangys/leafcutter_plot/server.R#195]
  165: func
  125: drawPlot
  111: <reactive:plotObj>
   95: drawReactive
   82: origRenderFunc
   81: output$select_cluster_plot
    1: shiny::runApp
Warning: Error in make_gene_plot: unused argument (debug = F)
  170: print
  167: renderPlot [/public/home/yangjie/yangys/leafcutter_plot/server.R#209]
  165: func
  125: drawPlot
  111: <reactive:plotObj>
   95: drawReactive
   82: origRenderFunc
   81: output$select_gene_plot
    1: shiny::runApp
<img width="438" alt="微信图片_20240908213908" src="https://github.com/user-attachments/assets/6d172a84-5b45-4e46-9d18-40755e81b283">

**Comment by jackhump** [comment]
Try the standalone leafviz app: github.com/jackhump/leafviz

**Comment by Yang-Yingshan** [comment]
> 试试独立的 leafviz 应用程序：github.com/jackhump/leafviz

Thanks, the issue is solved

**Comment by jackhump** [comment]
Glad to hear it!
