### ISSUE TITLE
LeafCutter Intron Clustering Time

### ISSUE THREAD

**Issue by ronv-fishers** [davidaknowles/leafcutter#262]
Hello,

I'm analyzing RNA sequencing data of samples from every chromosome, and I'm trying to gauge the expected duration for the Intron Clustering process. In my recent analysis, processing 10 samples took approximately 62 seconds using 2 CPU cores and 7 GB of memory, and I was wondering if this seems reasonable? I thought this would be too quick, for reference, juncing took 50 minutes for 10 samples. 

Thank you for your time.

**Comment by jackhump** [comment]
clustering is very fast - we regularly do it on 100s of samples in a few minutes. Junction extraction is much slower.
