### ISSUE TITLE
LeafViz improvements

### ISSUE THREAD

**Issue by davidaknowles** [davidaknowles/leafcutter#27]
- [x] Hideable full width panel saying "Welcome to LeafViz" and some description of what this is, usage, and link to documentation on viewing your own data. 
- [x] Default landing to an interesting gene, e.g. Rbfox1
- [x] Gene view clusters labels currently overlap e.g. for Rbfox1, maybe print diagonally? (not Diagon Alley)
- [x] leafvis -> LeafVis (on menu bar)
- [x] Make logo and LeafViz link to homepage
- [x] Add data title somewhere, e.g. instead of “Differential splicing events” have “GTEx Brain vs Heart differential splicing events” (this is available as `experimentCode`)

**Comment by jackhump** [comment]
For 1., There is already a "welcome to LeafViz" panel present and a full description in the "About" section so I'm not sure how necessary that is.

5. what are we saying is the homepage here? The github repo for Leafcutter? The github repo for LeafViz?

**Comment by davidaknowles** [comment]
1. Jonathan's feeling on the panel was that it's still not obvious what's going on when you originally get to the app. Plus that right hand panel with "Welcome to..." won't be visible if we default to showing some cluster (I guess that's why you removed that comment)
5. I think it makes sense if "LeafViz" links to the "About" tab. The logo can link to the main LeafCutter docs or also to "About".

**Comment by jackhump** [comment]
1,2,4 and 6 are now done, committed and deployed.

**Comment by davidaknowles** [comment]
Can you tick the boxes or just me?

**Comment by jackhump** [comment]
I can tick the boxes! Gene plots are no longer limited to the width of the screen and can increase depending on the length of the gene. RBFOX1 and any gene longer than 1E6bp will get a plot of width 5000px so as to properly see all the clusters. I'll be making more changes to the gene plot, such as highlighting which clusters belong to which coordinates in the gene, and sorting out the exons at each end, which are currently smooshed together.
