### ISSUE TITLE
update STAR params to reflect later versions of parameter options.

### ISSUE THREAD

**Issue by AMChalkie** [davidaknowles/leafcutter#36]
http://davidaknowles.github.io/leafcutter/articles/Usage.html (Differential splicing)

Alignment params : STAR --genomeDir hg19index/ --twopassMode --outSAMstrandField intronMotif --readFilesCommand zcat --outSAMtype BAM

No longer default in STAR STAR-2.5.3a.

Suggest: --twopassMode Basic 
Suggest: --outSAMtype BAM Unsorted **or** --outSAMtype BAM SortedByCoordinate

Depending on that leafcutter expects from STAR.

**Comment by davidaknowles** [comment]
I've added a note for the new version.
