### ISSUE TITLE
Improved documentation: Step 1. Prepare the LeafCutter differential splicing results for visualisation

### ISSUE THREAD

**Issue by AMChalkie** [davidaknowles/leafcutter#38]
This part is unclear and an example that exactly matched the results from http://davidaknowles.github.io/leafcutter/articles/Usage.html would be really helpful.

Rscript prepare_results.R --iFolder <iFolder> \
                         --oFolder <oFolder> \
                         --support <support> \
                         --annotation_code <annotation_code> \
                         --code <code> \
                         --FDR <FDR> \                       
iFolder - the folder that contains the results of the differential intron excision analysis. The script assumes all results share the same path and code.

oFolder - the folder where the results will be written.

support - the same support file as used for the previous analysis.

annotation_code - as before.

code - the same code used for the rest of the analysis, eg testYRIvsEU

FDR - the benjamini-hochberg false discovery rate with which to filter the results.

**Comment by davidaknowles** [comment]
Completely agree, and this interface needs cleaning up. 

For the example YRI vs EU data it should be something like this: 
```
../leafviz/prepare_results.R -i . -o for_leafviz --support test_diff_intron.txt --annotation_code ../leafviz/annotation_codes/gencode_hg19/gencode_hg19 --code leafcutter
```
but you'd need to move testYRIvsEU_perind_numers.counts.gz to leafcutter_perind_numers.counts.gz which we shouldn't require.

**Comment by davidaknowles** [comment]
This is done. The interface to `prepare_results.R` is simplified, the dependence on `bedtools` has been removed and the documentation shows how to run the example from `Usage`.

**Comment by zhengjiantao** [comment]
@davidaknowles 
May I ask if I need to get the FDR value of each intron instead of cluster, does leafcutter provide the corresponding code?
