### ISSUE TITLE
Error in covariate analysis when using smart initialization

### ISSUE THREAD

**Issue by ddpinto** [davidaknowles/leafcutter#39]
Hello,
Running leafcutter using covariates with the latest git code gives the following error message:
Error in solve.default(t(xNull) %*% xNull, t(xNull) %*% y_norm): system is computationally singular: reciprocal condition number = ###

Running without covariates or with random initialization gives no errors. Any ideas what the issue may be?

Thanks!

**Comment by davidaknowles** [comment]
It means the null model X matrix is numerically singular. The situation where a covariate doesn't vary for the samples tested for a given cluster is checked for. Do you have a lot of covariates included? If (number of covariates + 1) > (number of samples with enough coverage for this cluster) then I could see this happening (it's probably not a good situation for the Dirichlet-Multinomial GLM either).

**Comment by davidaknowles** [comment]
This would also be a problem if any of your covariates are co-linear. Is that obviously the case for your data? I can reproduce the error by just having two identical covariates. I'm going to add some regularization which should fix this.

**Comment by davidaknowles** [comment]
Ok I pushed this, let me know if it doesn't fix things for you.

**Comment by davidaknowles** [comment]
Maybe also interesting to note: adding a covariate twice doesn't effect things much but it does mess things up for a small number of clusters (showing -log10 p-values):
![image](https://user-images.githubusercontent.com/4521734/30619194-fac5840a-9d52-11e7-90db-d6ddd6f64390.png)
