### ISSUE TITLE
feature request: Make leafcutter agnostic of chromosome identifiers

### ISSUE THREAD

**Issue by shoersch** [davidaknowles/leafcutter#42]
Hi,

It would be fantastic - essential for me ;) -  if leafcutter could process non-human or non-standard chromosome identifiers.  Currently, it cannot, as per this line in leafcutter_cluster.py: chromLst = ["chr%d"%x for x in range(1,23)]+['chrX','chrY']+["%d"%x for x in range(1,23)]+['X','Y'] 
and skipping everything else entirely ( if chrom not in chromLst: continue ).
Use cases for this request abound and include:
- organisms with chromosome counts exceeding the number 23 (zebrafish, dog, cow...)
- organisms with different chr. naming schemes (cat, fruit fly, nematode)
- unplaced scaffolds, alternate versions (haplotypes)
- alignments against genome assemblies using different identifiers (e.g. NC_000075.6 via NCBI)

Arguably, leafcutter should make no assumptions whatsoever as to how chromosomes are identified.

Chromosome IDs could be provided by the user in a file, or (much preferred!) be generated on the fly based on a digest of the .junc files generated before, as per a preprocessing step based on something like:  cut -f1  *.junc | sort | uniq 

Thanks much,
Sebastian

PS: Related to issue #25

**Comment by goldenflaw** [comment]
Could you try to remove this line for your purposes?

Yang

**Comment by shoersch** [comment]
Thanks much - so, commenting out instances of "chromLst =  " and corresponding "if chrom not in chromLst:"  statements (2 instances, I think - in "pool_junc_reads" and in "sort_junctions" ), allows the script to run, apparently ok (although I haven't evaluated thoroughly!), now producing clusters with the non-standard chr IDs etc.

Could this, then, be made a user parameter? For now, I can live with this hack, but I would be very concerned, if I had to re-hack this script every time a new version of leafcutter comes around...

Sebastian

**Comment by goldenflaw** [comment]
Thanks, we'll discuss among us whether we should remove these checks
altogether. We can certainly put a flag that allows you to bypass this
check.

Yang

**Comment by shoersch** [comment]
Awesome! Thanks so much for prompt replies. Staying tuned.

**Comment by stephenrdoyle** [comment]
Hey @shoersch - are you happy to share your code fix for this?

Cheers, 
Steve

**Comment by goldenflaw** [comment]
We have added a new script leafcutter_cluster_regtools.py which has this fixed. You'll need to use regtools to extract junctions, however. This is not totally compatible with the differential splicing function, as we also added strands. If you want to use this script for differential splicing, you currently have to remove the strand info yourself (just remove :+ and :- from the cluster ID)
