### ISSUE TITLE
"all.introns$ensemblID" related error during preparing results using leafviz/prepare_results.R 

### ISSUE THREAD

**Issue by maegsul** [davidaknowles/leafcutter#45]
Hi all,

Thanks for developing LeafCutter, it works great for my dataset so far! However, I have an issue with leafviz/prepare_results.R scripts for visualizing the results.

I tried both annotation files provided by you and the annotation files I've created; but I am receiving the following error anyway:

> Loading required package: leafcutter
> Loading required package: Rcpp
> 
> Attaching package: âdplyrâ
> 
> The following objects are masked from âpackage:data.tableâ:
> 
>     between, first, last
> 
> The following objects are masked from âpackage:statsâ:
> 
>     filter, lag
> 
> The following objects are masked from âpackage:baseâ:
> 
>     intersect, setdiff, setequal, union
> 
> Preparing for visualisation
> Results to be saved in: OLBE
> Using annotation at: /home/fahri/leafcutter_RNASeq_LCL_77/leafcutter/leafviz/gencode_hg19_fk/gencode_hg19_fk
> Loading counts from RNAseq_brainFC_d12938out_perind_numers.counts.gz
> Loading metadata from RNASeq_brainFC_diff_intron_withCOV_d12938out.txt
> Loading exons from /home/fahri/leafcutter_RNASeq_LCL_77/leafcutter/leafviz/gencode_hg19_fk/gencode_hg19_fk_all_exons.txt.gz
> Read 999773 rows and 10 (of 10) columns from 0.096 GB file in 00:00:03
> Read 999773 rows and 10 (of 10) columns from 0.096 GB file in 00:00:03
> Read 999773 rows and 10 (of 10) columns from 0.096 GB file in 00:00:03
> [1] "Annotating junctions"
> [1] "Preparing results"
> Warning message:
> In is.na(all.introns$ensemblID) :
>   is.na() applied to non-(list or vector) of type 'NULL'
> Error in `$<-.data.frame`(`*tmp*`, transcripts, value = ".") :
>   replacement has 1 row, data has 0
> Calls: $<- -> $<-.data.frame
> Execution halted

Is it related to the fact that the annotation files do not have a header (except the exon file), hence there is no all.introns$ensemblID ? Or something else (high likely)? Do you have any idea what the problem could be?

Thanks in advance!

**Comment by jackhump** [comment]
Dear Fahri,

I'm sorry for this problem. I am currently away and will endeavour to look into this after the new year.

From: Fahri Küçükali
Sent: Wednesday, 20 December, 12:41
Subject: [davidaknowles/leafcutter] "all.introns$ensemblID" related error during preparing results using leafviz/prepare_results.R (#45)
To: davidaknowles/leafcutter
Cc: Subscribed


Hi all,
Thanks for developing LeafCutter, it works great for my dataset so far! However, I have an issue with leafviz/prepare_results.R scripts for visualizing the results.
I tried both annotation files provided by you and the annotation files I've created; but I am receiving the following error anyway:
Loading required package: leafcutter
Loading required package: Rcpp
Attaching package: âdplyrâ
The following objects are masked from âpackage:data.tableâ:
between, first, last
The following objects are masked from âpackage:statsâ:
filter, lag
The following objects are masked from âpackage:baseâ:
intersect, setdiff, setequal, union
Preparing for visualisation
Results to be saved in: OLBE
Using annotation at: /home/fahri/leafcutter_RNASeq_LCL_77/leafcutter/leafviz/gencode_hg19_fk/gencode_hg19_fk
Loading counts from RNAseq_brainFC_d12938out_perind_numers.counts.gz
Loading metadata from RNASeq_brainFC_diff_intron_withCOV_d12938out.txt
Loading exons from /home/fahri/leafcutter_RNASeq_LCL_77/leafcutter/leafviz/gencode_hg19_fk/gencode_hg19_fk_all_exons.txt.gz
Read 999773 rows and 10 (of 10) columns from 0.096 GB file in 00:00:03
Read 999773 rows and 10 (of 10) columns from 0.096 GB file in 00:00:03
Read 999773 rows and 10 (of 10) columns from 0.096 GB file in 00:00:03
[1] "Annotating junctions"
[1] "Preparing results"
Warning message:
In is.na(all.introns$ensemblID) :
is.na() applied to non-(list or vector) of type 'NULL'
Error in $<-.data.frame(*tmp*, transcripts, value = ".") :
replacement has 1 row, data has 0
Calls: $<- -> $<-.data.frame
Execution halted
Is it related to the fact that the annotation files do not have a header (except the exon file), hence there is no all.introns$ensemblID ? Or something else (high likely)? Do you have any idea what the problem could be?
Thanks in advance!

**Comment by jackhump** [comment]
So this was due to a chromosome name mismatch between two of the results files produced by leafcutter_ds.R 

This has now been fixed.
