### ISSUE TITLE
effect_sizes.txt file empty

### ISSUE THREAD

**Issue by gdoura** [davidaknowles/leafcutter#5]
Dear developers,
I have tried the program with only 2 files WT and KO feeding the correct bam.junc file et the leafcutter_ds_effect_sizes.txt remains empty, is it a normal behavior due to the presence of only 1 replicate for each sample to be analysed for differential splicing ?

Any help would be greatly appreaciated.
Best

**Comment by davidaknowles** [comment]
Interesting: we haven't tried one vs. one (the smallest we've tested is 4 vs. 4), I'll try to check this soon.

**Comment by gdoura** [comment]
Ok thank you for looking at this ! 
Best

**Comment by davidaknowles** [comment]
To run with just one sample both the min_samples_per_intron and min_samples_per_group need to be set to 1. You can do this with e.g.
./leafcutter_ds.R -g 1 -i 1 ...
I would take the p-values when you have no replicates with a (large) grain of salt. Out of curiosity I ran brain vs. muscle comparing N=220 to N=2 (i.e. no replicates as in your setting), and the p-values for both are certainly highly correlated (see attached). 
![image](https://cloud.githubusercontent.com/assets/4521734/15161671/f3461496-16b3-11e6-92a3-74c1ea46f45d.png)

**Comment by davidaknowles** [comment]
I've also added a check that the sample size of the smallest group is not below min_samples_per_intron or min_samples_per_group.

**Comment by gdoura** [comment]
I don't if I could leave a message after it has been closed
I'm trying just to thank you very much. I will give it a try. 
Best

**Comment by gdoura** [comment]
I've tried the program (on Mac El Capitan) with my 2 samples KO vs WT and checked for the presence of my positive control (floxed exon) found it with p > 0.07, as you said it was expected because of no replicate. I will try with a triplicate. excellent performance. Would be good to have the genomic coordinate on the figure also the gene name sometimes is too close to the border need a small shift to the right. Thank you very much. 
Best

**Comment by davidaknowles** [comment]
Thanks for the feedback! I agree those changes would be nice for the plots, I'll let you know if I get that done.
