### ISSUE TITLE
clustering does not works on other organism

### ISSUE THREAD

**Issue by kentnf** [davidaknowles/leafcutter#50]
the clustering does not work one other organism due to the chromosome list only accept number and x,y 
line 25 of leafcutter_cluster.py
`chromLst = ["chr%d"%x for x in range(1,23)]+['chrX','chrY']+["%d"%x for x in range(1,23)]+['X','Y']`
could you please update it?

**Comment by goldenflaw** [comment]
In the most recent version, there should be a flag that removes this check.

Best,
Yang
