### ISSUE TITLE
Does the leafcutter works for time series experiment? 

### ISSUE THREAD

**Issue by kentnf** [davidaknowles/leafcutter#51]
Hi, 
I have RNA-Seq samples from tomato fruit development stages. I want to identify sig changed AS from these stages.  In the example of leafcutter, I can only make comparisons such as:
stage 1 vs stage 2
stage 2 vs stage 3
stage 1 vs stage 3. 

How can I perform statistical analysis in a time-series way? 
Thanks.

**Comment by goldenflaw** [comment]
There is no statistical test for this. What you can do it to quantify
splicing in all your samples using LeafCutter, and use the estimated intron
usage as input to any statistical test that you may have developed.

Best,
Yang

**Comment by kentnf** [comment]
Thank you for quick reply. Is this file [name]_perind_numers.counts.gz should be used for any other statistical test software like DESeq?

**Comment by goldenflaw** [comment]
Sure, or the one without numers.

Best,
Yang

**Comment by kentnf** [comment]
Thanks again.

Best,
Yi
