### ISSUE TITLE
chrX and chrY skipped in prepare_phenotype_table.py

### ISSUE THREAD

**Issue by snaqvi1990** [davidaknowles/leafcutter#52]
Hi,

I noticed that prepare_phenotype_table.py excludes the X and Y chromosome when writing PSI values by chromosome. I have temporarily 'hacked' the script by setting chrX as chr23 and chrY as chr24, but is there any chance chrX and chrY could be included in the by chromosome output?

Thanks,
Sahin

**Comment by goldenflaw** [comment]
In the most recent version of LeafCutter, there is a flag that you can use
to remove the check for chromosome name.

Best,
Yang

**Comment by snaqvi1990** [comment]
How can I install this most recent version? I just re-cloned leafcutter, and there doesn't seem to be that option in prepare_phenotype_table:

git clone https://github.com/davidaknowles/leafcutter
python /lab/page/snaqvi/scripts/leafcutter/scripts/prepare_phenotype_table.py -h
Usage: prepare_phenotype_table.py [-p num_PCs] input_perind.counts.gz

Options:
  -h, --help           show this help message and exit
  -p NPCS, --pcs=NPCS  number of PCs output

**Comment by goldenflaw** [comment]
It is an option in the leafcutter_cluster step. We don't recommend using
the X/Y chromosome for QTL mapping as we haven't tested it.

Best,
Yang

**Comment by summike** [comment]
@snaqvi1990 
Hi Sahin,
I currently also need to analyze the sex chromosome. May I know after changing chrX, chrY into chr23,chr24 respectively, what have you edited in prepare_phenotype_table.py file?
Thank you very much!

Best wishes,
Mike

**Comment by davidaknowles** [comment]
The relevant option is `--checkchrom` in `leafcutter_cluster.py`. The default is actually False so this should solve the problem.
