### ISSUE TITLE
Running quantify_psi, with ref to issue 34

### ISSUE THREAD

**Issue by agiusp** [davidaknowles/leafcutter#53]
Hi David

I have successfully run leafcutter for a differential analysis of splicing events across some samples that we have. The instructions were wonderfully clear and the results are compelling - thank you! I am now trying to retrieve the raw ratios or PSI scores per sample that would give us a bit more insight beyond the delta_psi output by differential leafcutter. I followed the discussion on issue 34 and tried, unsuccessfully, to run your quantify_psi script listed there. Is this the right script to use? I used the junc_clustering_perind_numers.counts matrix (output from the clustering algorithm) as input, script runs but the result is an object with the following message repeated over and over: requires numeric/complex matrix/vector arguments
Any advice?

Thanks!

**Comment by davidaknowles** [comment]
Sorry I missed this. 

You could use `quantify_psi` but we now also include the "raw" ratios in the differential splicing output, hopefully that covers what you need.
