### ISSUE TITLE
leafcutter_ds.R not recognizing other organism .txt.gz exon file

### ISSUE THREAD

**Issue by mh406910** [davidaknowles/leafcutter#54]
Hello,

I have tried converting USCS, Ensembl and gencode mm10 (mm14 for gencode) .gtf files to the .txt.gz using the gtf_to_exons.R script but when I run leafcutter_ds.R I get an error that the file does not exist even though I am passing the correct location/directory for the generate .txt.gz

**Comment by mh406910** [comment]
@jackhump

**Comment by jackhump** [comment]
this is related to #47
