### ISSUE TITLE
leafcutter still not recognizing mm10 .txt.gz file in leafcutter_ds.R

### ISSUE THREAD

**Issue by mh406910** [davidaknowles/leafcutter#55]
I tried re-running with de-bugged leafcutter_cluster.py but I am still gettting this error when running leafcutter_ds.R 
Loading required package: Rcpp
Error in parse_args(OptionParser(usage = "%prog [options] counts_file groups_file",  :
  required at most 2 positional arguments, got 3
Execution halted

I used your gtf_2_exon.R on the gencode.vM14.annotation.gtf.gz

subsequently this .txt.gz file will not work in the plotting splice junctions as using the Leafcutter Shiny App @davidaknowles @jackhump

**Comment by mh406910** [comment]
@jackhump @davidaknowles

**Comment by goldenflaw** [comment]
Could you post first 5 lines of your count file?
Thanks,
Yang

**Comment by mh406910** [comment]
P40M3M4Wt_merged.sorted.filtered.bam P14M3M4Mut_merged.sorted.filtered.bam P40M3M4Mut_merged.sorted.filtered.bam P14M3M4Wt_merged.sorted.filtered.bam P40M3M4Het_merged.sorted.filtered.bam P14M3M4Het_merged.sorted.filtered.bam
chrX:7186335:7188532:clu_1_- 18 48 13 51 16 40
chrX:7186335:7212864:clu_1_- 5 12 8 10 10 9
chrX:7638728:7639858:clu_2_- 55 91 93 97 64 93
chrX:7639363:7639858:clu_2_- 10 5 11 12 5 8
chrX:7645199:7648557:clu_3_- 2204 2760 2411 2922 2277 2962
chrX:7645199:7651837:clu_3_- 7 10 6 9 10 9
chrX:7648887:7651837:clu_3_- 1374 1634 1762 1825 1637 1968
chrX:7722378:7723849:clu_4_- 25 36 31 35 51 36
chrX:7723753:7723849:clu_4_- 15 10 15 12 17 17
chrX:7765620:7766555:clu_5_- 46 52 66 62 47 59
@goldenflaw

**Comment by goldenflaw** [comment]
We've just upgraded the clustering script so that it shows the strand,
could you try to remove _+ and _- from the file and try again? Apologies
for this.

Yang

**Comment by mh406910** [comment]
I removed  the _+ and _- and I still got this message: 
Error in parse_args(OptionParser(usage = "%prog [options] counts_file groups_file",  :
  required at most 2 positional arguments, got 3
Execution halted
@goldenflaw

**Comment by goldenflaw** [comment]
Ok, thanks, @jackhump could you have a look?

Best,
Yang

**Comment by mh406910** [comment]
Also I get this error when I try to run ds_plots.R:
gz /home/seyfim/lustre/LeafCutter/data/output_files/test_diff_introns_P14WtMut.txt /home/seyfim/lustre/LeafCutter/data/output_files/leafcutter_ds_cluster_significance.txt -f 0.05
Loading required package: Rcpp
Loading counts from /home/seyfim/lustre/LeafCutter/data/output_files/test_perind_numers.counts.gz
Loading metadata from /home/seyfim/lustre/LeafCutter/data/output_files/test_diff_introns_P14WtMut.txt
Warning message:
In read.table(groups_file, header = F, stringsAsFactors = F) :
  incomplete final line found by readTableHeader on '/home/seyfim/lustre/LeafCutter/data/output_files/test_diff_introns_P14WtMut.txt'
Loading exons from /home/seyfim/lustre/LeafCutter/data/output_files/gencode.txt.gz
Error in `[.data.frame`(counts, , meta$sample) :
  undefined columns selected
Calls: [ -> [.data.frame
Execution halted
@goldenflaw @jackhump

**Comment by mh406910** [comment]
Hello @jackhump,
I tried pulling the latest version and rerunning my code and I got the following error when running leafcutter_ds.R:
Loading required package: Rcpp
Error in parse_args(OptionParser(usage = "%prog [options] counts_file groups_file",  :
  required at most 2 positional arguments, got 3
Execution halted

**Comment by mh406910** [comment]
Here's my code: 
/home/seyfim/lustre/LeafCutter/scripts/leafcutter-master/scripts/leafcutter_ds.R --num_threads 4 exon_file=/home/seyfim/lustre/LeafCutter/data/output_files/mm10.txt.gz /home/seyfim/lustre/LeafCutter/data/output_files/test_perind_numers.counts.gz  /home/seyfim/lustre/LeafCutter/data/output_files/P40WtMut.txt -i 1 -g 1

**Comment by mh406910** [comment]
I am getting output files from leafcutter_ds.R when I run the command with the exon_file= option but when I supply that output to ds_plots.R I get the following error:
Loading required package: Rcpp
Loading counts from /home/seyfim/lustre/LeafCutter/data/output_files/test_perind_numers.counts.gz
Loading metadata from /home/seyfim/lustre/LeafCutter/data/output_files/P14WtMut.txt
Warning message:
In read.table(groups_file, header = F, stringsAsFactors = F) :
  incomplete final line found by readTableHeader on '/home/seyfim/lustre/LeafCutter/data/output_files/P14WtMut.txt'
Loading exons from /home/seyfim/lustre/LeafCutter/data/mm10_ens.txt.gz
Saving 0 plots to ds_plots.pdf
null device
          1
All done, exiting

**Comment by mh406910** [comment]
Here is my command:/home/seyfim/lustre/LeafCutter/scripts/leafcutter-master/scripts/ds_plots.R -e /home/seyfim/lustre/LeafCutter/data/mm10_ens.txt.gz /home/seyfim/lustre/LeafCutter/data/output_files/test_perind_numers.counts.gz /home/seyfim/lustre/LeafCutter/data/output_files/P14WtMut.txt /home/seyfim/lustre/LeafCutter/data/output_files/leafcutter_ds_cluster_significance.txt -f 0.05

**Comment by Rohit-Satyam** [comment]
No solution was offered for this. The issue persists.

```
Loading required package: Rcpp
Loading counts from AL.vs.EM_perind_numers.counts.gz
Loading metadata from groups_file.txt
Error in `[.data.frame`(counts, , meta$sample) :
  undefined columns selected
Calls: [ -> [.data.frame
Execution halted

```

**Comment by Rohit-Satyam** [comment]
You should really include `meta$sample <- basename(meta$sample)` in `leafcutter_ds.R` file before line `counts=counts[,meta$sample]` line. Also, since the  `leafcutter_ds.R`  does not use actual bam files (rather just uses their names to subset count matrix) this should be explicitly mentioned in the manual. I tried giving the path of bam files thinking they will be used at this step. This can really help starters. Having said that you can always modify your name (since star bam file names are big) and remember giving the same names in your groups.txt file.

**Comment by Aynur31** [comment]
> meta$sample <- basename(meta$sample)

Thank you for this response. I followed your advice in this issue , but still could not solve this.
Can anyone help me ? I am new to this field , any advice is greatly appreciated. 
Here is my code:```
(leafcutter2.19) [akashgari19@login03 IL6]$ /kuacc/users/akashgari19/biosoft/leafcutter/scripts/leafcutter_ds.R --num_threads 4 testYRIvsEU_perind_numers.counts.gz IL6groups_file.txt
Loading required package: Rcpp
Warning messages:
1: replacing previous import ‘dplyr::combine’ by ‘gridExtra::combine’ when loading ‘leafcutter’ 
2: replacing previous import ‘dplyr::filter’ by ‘stats::filter’ when loading ‘leafcutter’ 
3: replacing previous import ‘dplyr::lag’ by ‘stats::lag’ when loading ‘leafcutter’ 
Loading counts from testYRIvsEU_perind_numers.counts.gz 
Loading metadata from IL6groups_file.txt 
Error in `[.data.frame`(counts, , meta$sample) : 
  undefined columns selected
Calls: [ -> [.data.frame
Execution halted
```
I already added meta$sample <- basename(meta$sample) to leafcutter_ds.R, but still got the same error message. 
Here is my data and metadata 
(leafcutter2.19) [akashgari19@login03 IL6]$ zcat testYRIvsEU_perind_numers.counts.gz | head
CON-2Aligned.sortedByCoord.out.bam IL6-1Aligned.sortedByCoord.out.bam CON-1Aligned.sortedByCoord.out.bam IL6_2Aligned.sortedByCoord.out.bam
X:6400170:6520793:clu_1_+ 0 0 3 9
X:6400261:6520793:clu_1_+ 33 6 15 9
X:6415860:6520793:clu_1_+ 0 6 12 6
X:7697395:7698493:clu_2_+ 147 186 177 180
X:7697395:7698507:clu_2_+ 6 0 0 0
X:7697526:7698493:clu_2_+ 0 9 9 0
X:7698880:7702063:clu_3_+ 135 225 213 186
X:7698964:7702063:clu_3_+ 0 0 6 0
X:7722230:7723849:clu_4_+ 0 0 0 18

(leafcutter2.19) [akashgari19@login03 IL6]$ head IL6groups_file.txt
CON-1Aligned.sortedByCoord.out.bam Control
CON-2Aligned.sortedByCoord.out.bam Control
IL6-1Aligned.sortedByCoord.out.bam IL6
IL6-2Aligned.sortedByCoord.out.bam IL6

Can you please help me ?
It`s been so hard working with leafcutter for a beginner. 
Looking forward to hearing from you.
