### ISSUE TITLE
Problems recreating results from the example

### ISSUE THREAD

**Issue by npeschke** [davidaknowles/leafcutter#57]
I ran the code of steps 1 and 2 in the Usage section of the tutorial on the provided data, however running the script `leafcutter_cluster.py` provides a different file compared to the tutorial:

`zcat testYRIvsEU_perind_numers.counts.gz | head`
> RNA.NA06986_CEU.chr1.bam RNA.NA06994_CEU.chr1.bam RNA.NA18486_YRI.chr1.bam RNA.NA06985_CEU.chr1.bam RNA.NA18487_YRI.chr1.bam RNA.NA06989_CEU.chr1.bam RNA.NA06984_CEU.chr1.bam RNA.NA18488_YRI.chr1.bam RNA.NA18489_YRI.chr1.bam RNA.NA18498_YRI.chr1.bam
> chr1:880180:880422:clu_1_- 38 9 56 44 23 1 28 24 14 5
> chr1:880180:880437:clu_1_- 3 6 15 17 4 0 3 11 4 1
> chr1:999969:1001210:clu_2_- 42 23 12 5 4 25 7 14 27 8
> chr1:999969:1001329:clu_2_- 17 10 2 8 1 6 6 4 17 4
> chr1:1274033:1274667:clu_3_- 10 3 9 6 4 3 6 2 11 8
> chr1:1274033:1274742:clu_3_- 9 7 9 6 6 0 3 6 6 9
> chr1:1310170:1310377:clu_4_- 10 3 42 48 23 0 16 6 2 0
> chr1:1310170:1310534:clu_4_- 40 19 163 313 112 0 60 58 13 14
> chr1:1326245:1328776:clu_5_- 6 25 21 10 6 8 7 4 11 20

versus the data from the tutorial

> RNA.NA06986_CEU.chr1.bam RNA.NA06994_CEU.chr1.bam RNA.NA18486_YRI.chr1.bam RNA.NA06985_CEU.chr1.bam RNA.NA18487_YRI.chr1.bam RNA.NA06989_CEU.chr1.bam RNA.NA06984_CEU.chr1.bam RNA.NA18488_YRI.chr1.bam RNA.NA18489_YRI.chr1.bam RNA.NA18498_YRI.chr1.bam
> chr1:17055:17233:clu_1 21 13 18 20 17 12 11 8 15 25
> chr1:17055:17606:clu_1 4 11 12 7 2 0 5 2 4 4
> chr1:17368:17606:clu_1 127 132 128 55 93 90 68 43 112 137
> chr1:668593:668687:clu_2 3 11 1 3 4 4 8 1 5 16
> chr1:668593:672093:clu_2 11 16 23 10 3 20 9 6 23 31

could anybody tell me the commit used to create the data from the tutorial?
Best regards
Nicolas

**Comment by goldenflaw** [comment]
I may have identified the problem: the strand information in the
GEUVADIS bam files are wrong (random). Thus adding the requirement
that junctions are on the same strand causes this mismatch. We will
investigate whether this affects bam files generated using STAR with
--outSAMstrandField intronMotif too. For now I would recommend using a
previous version of the clustering method without strand information.

Best,
Yang

**Comment by npeschke** [comment]
Thank you very much using version v0.2.7 solved the issue for me!
Best regards
Nicolas
