### ISSUE TITLE
LeafViz Gene-level vizualization: Error: nrow(myclusters) > 0 is not TRUE

### ISSUE THREAD

**Issue by drevansa** [davidaknowles/leafcutter#61]
Hello there, 

I am encountering a couple of issues with the Gene-level visualization panel of LeafViz.

Re: Error: nrow(myclusters) > 0 is not TRUE

The nrow(myclusters) error is generated in an inconsistent manner when running run_leafviz.R with the same leafviz.RData:
A) A splicing event visualization plot is generated successfully for a gene, but a gene-level plot fails in one session, but not a second session.
B) A splicing event-plot is generated for but the gene-level plot fails, but after viewing gene-level plots for other genese, the failing gene will, in the same session, produce a plot.

prepare_results.R  ran without any warnings or errors.

run_leafviz.R  output with an example fail:

./run_leafviz.R $ANALYSISDIR/leafviz/$ANALYSIS"_leafviz.RData"
Attaching package: ‘dplyr’
The following objects are masked from ‘package:stats’:
    filter, lag
The following objects are masked from ‘package:base’:
    intersect, setdiff, setequal, union
Attaching package: ‘DT’
The following objects are masked from ‘package:shiny’:
    dataTableOutput, renderDataTable
Attaching package: ‘gridExtra’
The following object is masked from ‘package:dplyr’:
    combine
[1] "Loading results from .../leafviz.RData"
Listening on http://......

Attaching package: ‘shinyjs’
The following object is masked from ‘package:intervals’:
    show
The following object is masked from ‘package:Rcpp’:
    show
The following object is masked from ‘package:shiny’:
    runExample
The following objects are masked from ‘package:methods’:
    removeClass, show

TableGrob (2 x 1) "arrange": 2 grobs
  z     cells    name           grob
1 1 (1-1,1-1) arrange gtable[layout]
2 2 (2-2,1-1) arrange gtable[layout]
Warning: Error in : nrow(myclusters) > 0 is not TRUE
Stack trace (innermost first):
    104: stopifnot
    103: make_gene_plot
    102: print
    101: withCallingHandlers
    100: suppressWarnings
     99: renderPlot [/Users/anna/bin/leafcutter/leafviz/server.R#209]
     89: <reactive:plotObj>
     78: plotObj
     77: origRenderFunc
     76: output$select_gene_plot
      1: shiny::runApp

I can send more information if you let me know what would be useful?

**Comment by jackhump** [comment]
Hi, thanks for using Leafcutter. Sorry to hear about these problems. Just to check, can you confirm this:
1. you are using the most recent version of Leafcutter 
2. you have reinstalled the R package and are using R >= 3.2
3. the data you are trying to visualise has all been processed with the same version of Leafcutter

These questions are useful for me:
* what species are you working with?
* can you confirm which annotation file you used?
* is the genome you aligned to is compatible with the annotation you're using? weird chromosome naming conventions are a common source of problems.

**Comment by drevansa** [comment]
Hi Jack,
Thank you very much for getting back to me - these aren't major problems, just thought you may want to know about them.

1) I have run on two leafcutter installs and encounterd the gene-level plot synonym issue running on both, and the gene-level nrow issue on the IMac, which 
was downloaded on 08/05/2010, so should be the latest version of leafcutter.

## MacBook Air - Mac OS Sierra
Leafcutter: download git clone https://github.com/davidaknowles/leafcutter 25/04/2018
R version: R 3.4.1 (2017-06-30) -- "Single Candle", Platform: x86_64-apple-darwin15.6.0 (64-bit)
Python 2.7.10
Samtools Version: 1.3 (using htslib 1.3)

## IMac - Mac OS El Capitan
Leafcutter: download git clone https://github.com/davidaknowles/leafcutter 08/05/2018
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch", Platform: x86_64-apple-darwin13.4.0 (64-bit)
Python 2.7.14_2
Samtools Version: 1.3 (using htslib 1.3)

2) I haven't reinstalled R as:
   leafcutter_ds.R ran without any warnings or errors.
   ds_plots.R ran with 11 warnings, which I haven't viewed, as I have just run from the command line.
   prepare_results.R  ran without any warnings or errors.

3) The data I am trying to visualize has all be processed with the same version of Leafcutter, most recently on IMac 10/05/2018.

4) I am using Leafcutter downloaded on 08/05/2018, run 10/05/2018.

5) I am working on homo sapien, using gencode_hg19 annotation sourced with: ./download_human_annotation_codes.sh

6) I have aligned with genecode_hg19 reference sourced from sanger [07/02/2018]
   curl -O  ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_19/GRCh37.p13.genome.fa.gz
   curl -O ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_19/gencode.v19.chr_patch_hapl_scaff.annotation.gtf.gz

Building star index as per STARmanual.pdf Section 2, 2.1. Basic options p4

STAR \
    --runThreadN 24 \
    --runMode genomeGenerate \
    --genomeDir $DATADIR \
    --genomeFastaFiles $DATADIR/GRCh37.p13.genome.fa \
    --sjdbGTFfile $DATADIR/gencode.v19.chr_patch_hapl_scaff.annotation.gtf \
    --sjdbOverhang 100


Mapping following your workflow, but with multiple fastq per sample, and passing in Read groups:

STAR \
    --genomeDir $STARINDEX \
    --twopassMode Basic \
    --outSAMstrandField intronMotif \
    --readFilesIn $FQ1LST $FQ2LST \
    --readFilesCommand zcat \
    --outSAMattrRGline $RGID1LST \
    --outSAMtype BAM Unsorted


Re: Gene-level plot - Synonym issue - Error: Aesthetics must be either length 1
I have only noticed this for LVRN / AQPEP so far, where these are both listed on Genecards as synonyms.
This plot fail is reproducible - I have also done a mapping with UCSC sourced hg19 reference and encountered the same issue.

Re: Gene-leve plot - Error: nrow(myclusters) > 0 is not TRUE
I only spotted this yesterday. The error was present, but not consistently reproducible for the same gene-plot using the same dataset (genecode ref mapped),
or a second dataset (ucsc ref mapped), so appeared session related?

The genes for which this arrose: TNS1 and CIDEC.

Hope this helps, and let me know if you need any more info, but I won't have access to the IMac install for the next few days.

I have a question or two regarding best practice recommendations for the handling of multi-mappers and PCR duplicates for leafcutter analysis, but I guess that would be better posted on your google forum?

Best wishes
Drevansa

**Comment by drevansa** [comment]
Sorry - I closed this in error.

**Comment by drevansa** [comment]
Hello,

I have done a complete reinstall and update of R (and mac dependencies, including clang, gfortran, xquartz, devtools, java etc), reinstalled Leafcutter using the latest download and the reported issue persists.

R version 3.5.0 (2018-04-23) -- "Joy in Playing"  Platform: x86_64-apple-darwin15.6.0 (64-bit)
Gene level plotting, in the same session of LeafViz fails in an inconsistent manner for the same gene working with the same dataset (generated with the new install). 
So I can happily plot a few genes without issue, then encounter a failure to plot, where the
"nrow(myclusters) > 0 is not TRUE" error is displayed in red in the plot field.
Then plot a different gene, and then return to the failed gene and plot successfully.

I've also encountered a server error when attempting to download plots that have generated successfully, where resuming a download (sometimes several times over) has ultimately allowed me to download.

Is the reported issue perhaps related to a server issue?

**Comment by JohnvonNeumannAlan** [comment]
I also meet the problem like `nrow(exons_chr) > 0 is not TRUE`

**Comment by davidaknowles** [comment]
@jackhump did you get anywhere with this?

**Comment by jackhump** [comment]
No, it's a weird intermittent bug.
Most of the time nrow(exons_chr) > 0 is not TRUE appears due to a lack of annotation over a particular region or a mismatch between chromosome names. 
But what @drevansa describes happens intermittently.
@drevansa sent me their .Rdata file to have a look at and I couldn't work out what's causing the problem. Sorry David.

**Comment by davidaknowles** [comment]
Thanks for looking at it @jackhump . 

Can one of you send me the .Rdata please?

**Comment by jackhump** [comment]
done

**Comment by davidaknowles** [comment]
You'll be SHOCKED to hear this was yet another chromosome naming bug (e.g. chr1 vs 1). Fixed now, just strips the leading 'chr' if it's there. It was random because we had a `sample` function that only looked at a subset of chromosome names so it would make a different decision if some other contigs (e.g. GL000220.1) got randomly selected.

**Comment by davidaknowles** [comment]
(the fix requires a leafcutter reinstall because it changes code in `make_gene_plot`)
