### ISSUE TITLE
Usage.html Typo Step 3. Differential intron excision analysis leafcutter_ds.R syntax

### ISSUE THREAD

**Issue by drevansa** [davidaknowles/leafcutter#62]
https://github.com/davidaknowles/leafcutter/blob/ff05d2ce86b943a3b1209cb4aabae434b3d8d9f7/docs/articles/Usage.html#L158

replace --exons_file  with --exon_file

Re conflict: ln 13  leafcutter_ds.R : make_option(c("-e","--exon_file")

Version 2.0, January 2004, sourced 25/04/2018
git clone https://github.com/davidaknowles/leafcutter

**Comment by davidaknowles** [comment]
Thanks this is fixed now.
