### ISSUE TITLE
Usage.html Step 3. Differential intron excision analysis - Typo 

### ISSUE THREAD

**Issue by drevansa** [davidaknowles/leafcutter#63]
https://github.com/davidaknowles/leafcutter/blob/ff05d2ce86b943a3b1209cb4aabae434b3d8d9f7/docs/articles/Usage.html#L146

replace test_diff_introns.txt  with test_diff_intron.txt

for compatibility with worked_out_example.sh: ln 39-40; 45, 50, 53
and Usage.html#L158

Version 2.0, January 2004, sourced 25/04/2018
git clone https://github.com/davidaknowles/leafcutter

**Comment by davidaknowles** [comment]
I changed this to `groups_file` now to be consistent with the `leafcutter_ds` naming.
