### ISSUE TITLE
Usage.html Step 3. Differential intron excision analysis: Groups are handled in lexical order

### ISSUE THREAD

**Issue by drevansa** [davidaknowles/leafcutter#64]
https://github.com/davidaknowles/leafcutter/blob/ff05d2ce86b943a3b1209cb4aabae434b3d8d9f7/docs/articles/Usage.html#L145

Re: "and the second is the column (what you call these is arbitrary, ....)."

Typo: "and the second is the group column ...."

Also, the group naming afects the order in which groups are processed.
So, for your example file: test_diff_introns.txt

RNA.NA18486_YRI.chr1.bam YRI
RNA.NA18487_YRI.chr1.bam YRI
RNA.NA18488_YRI.chr1.bam YRI
RNA.NA18489_YRI.chr1.bam YRI
RNA.NA18498_YRI.chr1.bam YRI
RNA.NA06984_CEU.chr1.bam CEU
RNA.NA06985_CEU.chr1.bam CEU
RNA.NA06986_CEU.chr1.bam CEU
RNA.NA06989_CEU.chr1.bam CEU
RNA.NA06994_CEU.chr1.bam CEU

Differential analysis will be CEU will be treated as the baseline, and YRI as the treatment/case (YRI vs CEU).
So downstream in leafviz gene-level plots, up and down regulation relate to YRI.

**Comment by drevansa** [comment]
Yes, just to document the behaviour as I think it may catch a few people out.

**Comment by davidaknowles** [comment]
Ok will do. I guess you're also saying it would be more intuitive if the baseline was the first group listed? That should be an easy change too.

**Comment by davidaknowles** [comment]
Ok I've changed the default behaviour and updated the docs.
