### ISSUE TITLE
LeafViz pca plot axis query 

### ISSUE THREAD

**Issue by drevansa** [davidaknowles/leafcutter#66]
Hello there,
I think there may be an issue with the LeafViz PCA plots generated from LeafCutter prepare_results.R RData set?

LeafViz plot for PC 1
[LeafViz_PCA_PC1_vs_PC2_query_1.pdf](https://github.com/davidaknowles/leafcutter/files/2001103/LeafViz_PCA_PC1_vs_PC2_query_1.pdf)

PCA results from the same RDataset:

Group  PC1        PC2
WAT  20.16620  -8.995684
WAT  20.81406  -4.443752
WAT  24.28214  -8.657540
WAT  23.91210 -11.858298
OAT -11.48259   2.032016
OAT -80.67444 -24.706885
OAT -12.14841  71.577739
WAT  17.91700  -4.975584
OAT -13.92228   5.285461
WAT  11.13622 -15.257471

summary(pca[[1]][1:2])
      PC1              PC2          
 Min.   :-80.67   Min.   :-24.7069  
 1st Qu.:-11.98   1st Qu.:-11.1426  
 Median : 14.53   Median : -6.8166  
 Mean   :  0.00   Mean   :  0.0000  
 3rd Qu.: 20.65   3rd Qu.:  0.4131  
 Max.   : 24.28   Max.   : 71.5777  

So, I was expecting something like this (group labels modified):
[LeafCutter_RData_PCA_PC1_vs_PC2_query_1.pdf](https://github.com/davidaknowles/leafcutter/files/2001113/LeafCutter_RData_PCA_PC1_vs_PC2_query_1.pdf)

Best wishes
Drevansa

**Comment by jackhump** [comment]
good spot Drevansa! I've found the bug, I'd got the x and y aesthetics the wrong way around.
