### ISSUE TITLE
prepare_results.R ln 368: exception handling replacement has 1 row, data has 0

### ISSUE THREAD

**Issue by drevansa** [davidaknowles/leafcutter#68]
https://github.com/davidaknowles/leafcutter/blob/7ad3ee1eba7a9bf6783f24b4a5b4b8f6aac91c9c/leafviz/prepare_results.R#L368

Hello, 

I have encountered the following error: 

`Error in '$<-.data.frame'('*tmp*', transcripts, value = ".") : `
`  replacement has 1 row, data has 0`
`Calls: $<- -> $<-.data.frame`
`Execution halted`

The error occurs on line 368 of prepare_results.R: 
`all.introns[ all.introns$transcripts == "", ]$transcripts <- "." `

This arrises for results where is an absence of null values in all.introns$transcripts

`all.introns[ all.introns$transcripts == "", ]$transcripts`
`character(0)`

This error occurred for a results set with a single entry where:

`str(all.introns)`
`$ transcripts       : chr  "ENST00000456556.5_1" "ENST00000456556.5_1+ENST00000534304.5_1+ENST00000295246.6_1+ENST00000528268.5_1" "ENST00000456556.5_1"`

As a work around I amended ln 368 of my local copy of the script:
`if (is.null(all.introns[ all.introns$transcripts == "", ]$transcripts )) { all.introns[ all.introns$transcripts == "", ]$transcripts <- "." }` 

This gets past the post, but I don't know how robust more generally for exception handling.

**Comment by davidaknowles** [comment]
This is now fixed using more robust `dplyr` code.
