### ISSUE TITLE
Using -g in conjunction with Rscript results in a warning and the value is not passed to the script

### ISSUE THREAD

**Issue by npeschke** [davidaknowles/leafcutter#73]
In `leafcutter_ds.R` there is an option 
`make_option(c("-g","--min_samples_per_group"), default=3, help="Require this many samples in each group to have at least min_coverage reads [default %default]")`

Calling Rscript with the script and -g results in the following warning and the value is not passed to the script. 
`Rscript leafcutter_ds.R -g 3`
`WARNING: unknown gui '3', using X11`

See also [this](https://stackoverflow.com/questions/36773260/off-limits-arguments-to-rscript) stackoverflow post on the matter

Best regards,
Nicolas

**Comment by jackhump** [comment]
This should be updated. @davidaknowles ? Can we just deprecate the -g flag and insist on the longer --min_samples_per_group ?

**Comment by davidaknowles** [comment]
What version of R are you running? I can't reproduce this on 3.5.0.

**Comment by npeschke** [comment]
I am using R 3.3.1

**Comment by davidaknowles** [comment]
Thanks. I don't really want to deprecate `-g` because other people may be using it. Glad you found a workaround.
