### ISSUE TITLE
tables not loading

### ISSUE THREAD

**Issue by neilihrke** [davidaknowles/leafcutter#74]
When I run  `Rscript run_leafviz.R` 

I first see this message:
Listening on http://127.0.0.1:4422
Couldn't get a file descriptor referring to the console

firefox doesn't load but i can manually enter the address and leafcutter loads, but 2 of the 3 tables do not load and when I give me errors.  See the attached screen shots.  

Did I miss something while installing?

![screen shot 2018-07-17 at 7 54 49 am](https://user-images.githubusercontent.com/16964682/42818594-e5ace92e-8996-11e8-98d0-f581293f28cb.png)
![screen shot 2018-07-17 at 7 54 38 am](https://user-images.githubusercontent.com/16964682/42818595-e5c7f73c-8996-11e8-8787-9c2bb5e40e67.png)

**Comment by jackhump** [comment]
Hi, 
what are the errors that the tables give you?
For the first point we are aware of the problem but are still not sure what this is caused by. What is your setup? Operating system, R version, etc. I developed the shiny app on mac OS X and google chrome so that may be the reason.

**Comment by neilihrke** [comment]
R version 3.4.3 (2017-11-30) 

$ python -V
Python 3.6.5 :: Anaconda, Inc.

Operating System: 
$ uname -a
Linux................#1 SMP Wed May 9 23:09:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Attached as  a pdf is my terminal output when running 
[leafcutter.pdf](https://github.com/davidaknowles/leafcutter/files/2202653/leafcutter.pdf)

I get a file not found error when clicking on 'save plot'
