### ISSUE TITLE
Shiny app error: nrow(exons_chr)>0 not TRUE 

### ISSUE THREAD

**Issue by lisavetasol** [davidaknowles/leafcutter#75]
Hi! 
Thank you a lot for your tools, it's so enjoyable!
I have some problems with the new shiny app - there is an error " nrow(exons_chr)>0 is not TRUE" in place where supposed to be "splicing event visualization" picture (see attached file). I using annotation files with NCBI names of chromosomes, maybe my error somehow related to this. 
Thank you in advance. 
Lisa
![image](https://user-images.githubusercontent.com/41292192/43642440-d9484e64-9727-11e8-8ac1-13462a044c37.png)

**Comment by jackhump** [comment]
Hi Lisa,

Can I ask which species and annotation you're using? We've found before this can happen sometimes with more unusual gene annotations.

On 3 Aug 2018 1:12 pm, lisavetasol <notifications@github.com> wrote:

Hi!
Thank you a lot for your tools, it's so enjoyable!
I have some problems with the new shiny app - there is an error " nrow(exons_chr)>0 is not TRUE" in place where supposed to be "splicing event visualization" picture. I using annotation files with NCBI names of chromosomes, maybe my error somehow related to this.
Thank you in advance.
Lisa

**Comment by lisavetasol** [comment]
Hi, 
I used rat annotation "ng-rat-Rnor_6.0-RefSeq-NCBI.gtf", where names of chromosomes look in normal RefSeq way (like "NC_005100.4"). Maybe it's better to somehow share this gtf with you? 
I also found out that the string "chr" was added to chromosomes names in the table called "introns" (something like "chrNC_005100.4"), however in the table called "exons_table" the names are original (without additional "chr").  
Thank you! 
Lisa

**Comment by jackhump** [comment]
Hi Lisa,
I have a feeling that the NCBI chromosome names are the problem. Would you mind trying the Ensembl annotation with the chr1, chr2, etc naming scheme instead?

**Comment by lisavetasol** [comment]
Hi! 
I figured out what was wrong. The problem is that in script "prepare_results.R" you add "chr" to introns, threeprime and fiveprime tables, but not to exons table. The additional line ( 'exons_table$chr <- leafcutter::add_chr(exons_table$chr)' ) after 84th line solved the problem.  The program still adds "chr" to names, but at least now it builds all pictures. 
Hope it will help! :) 
![image](https://user-images.githubusercontent.com/41292192/44389016-0243b000-a52a-11e8-92a5-30638a47d08c.png)

**Comment by jackhump** [comment]
Great spot, I've submitted a pull request to add that line into the prepare_results.R file.
