### ISSUE TITLE
[Leafcutter Shiny App] Step-1:invalid 'file' argument

### ISSUE THREAD

**Issue by JohnvonNeumannAlan** [davidaknowles/leafcutter#77]
`/Users/jieqianghe/leafcutter/leafviz/prepare_results.R /Users/jieqianghe/testYRIvsEU_perind_numers.counts.gz /Users/jieqianghe/leafcutter_ds_cluster_significance.txt /Users/jieqianghe/leafcutter_ds_effect_sizes.txt /Users/jieqianghe/gencode_hg19/gencode_hg19`
  
But it just shows the error：
`Error in file.exists(groups_file) : invalid 'file' argument`

**Comment by jackhump** [comment]
Hi! Make sure you put in your groups metadata file with -m <groups_file> before the positional arguments. Like so:

```
prepare_results.R -m <groups_file> <name>_perind_numers.counts.gz <name>_cluster_significance.txt <name>_effect_sizes.txt annotation_code 
```

We should make it clearer that you need to give a groups file.  Let me know if that works for you! :)

**Comment by davidaknowles** [comment]
This is fixed it seems.
