### ISSUE TITLE
R.utils 2.7.0 Error: 'evalWithTimeout' is defunct.Use 'R.utils::withTimeout()'

### ISSUE THREAD

**Issue by Lafond-LapalmeJ** [davidaknowles/leafcutter#79]
The error happen to me when I run leafcutter_ds.R with updated package R.utils 2.7.0.
It was working with older version of R.utils

**Comment by AldoCP** [comment]
I get the same error...

**Comment by gkumar09** [comment]
Hi, @Lafond-LapalmeJ is right. It requires R.utils version <2.7. It installed R.utils 2.6 version, and it worked fine.

**Comment by davidaknowles** [comment]
This is now fixed.
