### ISSUE TITLE
sQTL mapping: how to deal with 0/0

### ISSUE THREAD

**Issue by boxiangliu** [davidaknowles/leafcutter#8]
Hi David,

Thanks for making leafcutter available. I am wondering what your strategy is to deal with 0/0 in sQTL mapping. I have a few thoughts but none are quite optimal. The first one is to simply through these samples out (for the particular introns). However, neither matrix eQTL or fastqtl will be happy with missing data. Another thought is to consider them zero. However this perhaps does not reflect what is really going on. The final thought is to maybe use Laplace smoothing, making the proportion 1/N where N is the total number of introns in the cluster. The last one makes the most sense to me. 

Do you have any thoughts on this? 

Bosh

**Comment by davidaknowles** [comment]
Hi Bosh - I agree that statistically the correct thing to do is to exclude
that observation (that's what the Dirichlet-multinomial would do
implicitly). Yang maybe you can comment on how you did this with
matrixEQTL?

On 28 June 2016 at 11:17, Boxiang Liu <notifications@github.com> wrote:

> Hi David,
>
> Thanks for making leafcutter available. I am wondering what your strategy
> is to deal with 0/0 in sQTL mapping. I have a few thoughts but none are
> quite optimal. The first one is to simply through these samples out (for
> the particular intron). However, neither matrix eQTL or fastqtl will be
> happy with missing data. Another thought is to consider them zero. However
> this perhaps does not reflect what is really going on. The final thought is
> to maybe use Laplace smoothing, making the proportion 1/N where N is the
> total number of introns in the cluster.
>
> Do you have any thoughts on this?
>
> Bosh
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/davidaknowles/leafcutter/issues/8>, or mute the thread
> <https://github.com/notifications/unsubscribe/AET_Bhz4BHzEHNHD9BF-OfcveEXqSKqrks5qQWVLgaJpZM4JAYjS>
> .
>



-- 
David A. Knowles,
Stanford University.
E-mail: knowles84@gmail.com
Web: http://cs.stanford.edu/~davidknowles/

**Comment by goldenflaw** [comment]
You can try setting the value to the mean/median if not too many are
missing.

Yang

**Comment by boxiangliu** [comment]
That makes sense. Thank you!
