### ISSUE TITLE
Error in : nrow(exons_chr) > 0 is not TRUE

### ISSUE THREAD

**Issue by Wanpeng-Wang** [davidaknowles/leafcutter#80]
Hi, 
I'm running leafcutter on Drosophila RNAseq data. I'm using genome release 6.21 from flybase and generated all required annotation file from the same release. 
I had to make changes in several scripts to get chr names and gene_id to work. 
I'm getting 

> Error in : nrow(exons_chr) > 0 is not TRUE

 in the Splicing event visualization window. 

```
Warning: Error in : nrow(exons_chr) > 0 is not TRUE
  169: stop
  168: stopifnot
  167: make_cluster_plot
  163: renderPlot [/home/leafcutter/leafviz/server.R#195]
  161: func
  121: drawPlot
  107: <reactive:plotObj>
   91: drawReactive
   78: origRenderFunc
   77: output$select_cluster_plot
    1: shiny::runApp

```
And here is related chunk in server.R
  
```
  # PLOTTING
  
  output$select_cluster_plot <- renderPlot({
    plotTitle <- c(mydata()$gene, as.character(mydata()$cluster) )
    suppressWarnings( print(
      make_cluster_plot( mydata()$cluster,
                       main_title = plotTitle,
                       meta = meta,
                       cluster_ids = cluster_ids,
                       exons_table = exons_table,
                       counts = counts,
                       introns = introns)
    ))
  }, width = "auto", height = "auto",  res = 90
  )

  observeEvent(values$default,{ 
    output$select_gene_plot <- renderPlot({
    suppressWarnings( print( 
      make_gene_plot(mydata()$gene, counts = counts, introns = introns, exons_table = exons_table, cluster_list = clusters, clusterID = mydata()$cluster, introns_to_plot = introns_to_plot)
      )
    )
    }, width = mydata()$width, height = "auto", res = 90 # try changing height param
   )
  })
```
I cannot find where exons_chr is defined. Any ideas?

Thank you!

Wanpeng

**Comment by jackhump** [comment]
Hi Wanpeng,

exons_chr is defined in the plotting function leafcutter/R//make_cluster_plot.R. The code is pretty sloppy (I wrote it) and could definitely be refactored. We've had this problem come up a lot, usually when people are using species and annotations that we hadn't specifically tested - we only tested human and mouse with GENCODE annotation.

```
if (!is.null(exons_table)) {
    
    # find the exons
    exons_chr <- exons_table[ exons_table$chr==intron_meta$chr[1], ] # subset by chr
    
    stopifnot( nrow(exons_chr) > 0)
    
    exons_here <- exons_chr[ ( min(s) <= exons_chr$start & exons_chr$start <= max(s) ) | ( min(s) <= exons_chr$end & exons_chr$end <= max(s) ), ] # find exons

    # if exons found - remove exons that don't actually start or end with a junction
    # and any repeated exons or any exons larger than 500bp
    if( nrow(exons_here) > 0 ){ 
      exons_here <-  unique( 
        exons_here[ ( exons_here$end %in% intron_meta$start | 
                        exons_here$start %in% intron_meta$end ) &
                      ( exons_here$end - exons_here$start <= 500 |
                        exons_here$end == min(intron_meta$start) |
                        exons_here$start == max(intron_meta$end) ), ]
      )
    }
```

intron_meta is a dataframe created from the rownames of the junction count matrix that you give to prepare_results.R
exons_table is a dataframe created from the exons.txt.gz file you give to prepare_results.R

Do you get this error on every cluster or just some of the clusters?
If it's on every cluster then there's some systematic mismatch between those two tables.
If it's on the occasional cluster then it's probably some kind of annotation error.

I'd appreciate if you had any insight in to how we can fix this.

**Comment by Wanpeng-Wang** [comment]
Hi Jack,

Thanks for your response. The error occurs on every cluster. 
I did some backtracking and I suspect this line returned an empty data frame. 
   `y <- t(counts[ cluster_ids==cluster_to_plot, ])`

I'm a liitle bit lost here. What does the counts object look like at this point? 
Also, cluster_ids and cluster_to_plot are not in my final .Rdata file. 
Which scprits produce these files?

Thanks!

Wanpeng

**Comment by jackhump** [comment]
so cluster_ids should be in there as that's defined in prepare_results.R. It's a vector of cluster IDs for significant clusters. The positions of the IDs in that vector are in the same order and length as the rownames of the counts table so it's used to subset the counts table to just get the junctions that belong to that cluster.
cluster_to_plot is the variable that stores the selection made by the user in the Shiny app.
So when server.R calls the make_cluster_plot function, cluster_to_plot is the first argument passed to it. 

Could you paste in a few lines from your _perind_numers.counts.gz file and your <annotation_code>_all_exons.txt.gz file please? The most obvious thing would be some kind of mismatch between the two.

**Comment by goldenflaw** [comment]
The NAs should not be needed for plotting, is that correct?

Best,
Yang

**Comment by Wanpeng-Wang** [comment]
Yes, the NAs are not needed. I'd love to see where the name string is created. What information should be in its place?
Thank you for your time~

**Comment by leandroroser** [comment]
Hi,

 I am working with M. musculus and having the same issue. Might the problem be related with these lines in make_cluster_plot?:

```
 # make sure intron_meta has "chr" in front of chromosome name so it plays nice with the exon table
  if( all( ! grepl("chr", intron_meta$chr))){
    intron_meta$chr <- paste0("chr", as.character(intron_meta$chr))
  }
```
I can see that intron_meta has chromosome IDs starting with "chr", but exons_table does not (the Ensembl gtf has the chr field annotated as 1,2..), so adding the following lines below the previous ones, works for me:

```
 if(!is.null(exons_table)) {
  if( all(! grepl("chr", exons_table$chr))){
    exons_table$chr <- paste0("chr", as.character(exons_table$chr))
  }
```
Thanks,
   Leandro

**Comment by davidaknowles** [comment]
Thanks Leandro, I've added your suggestion to `make_cluster_plot`. 

Wanpeng can you let us know if that fixes your issue after a re-install of leafcutter?

**Comment by davidaknowles** [comment]
Closing this for now, please reopen if the problem persists.

**Comment by Wanpeng-Wang** [comment]
The problem persists. 
This is the error I got:
`Warning: Error in make_cluster_plot: nrow(exons_chr) > 0 is not TRUE
  170: <Anonymous>
`
