### ISSUE TITLE
running into an issue with dplyr

### ISSUE THREAD

**Issue by mforde84** [davidaknowles/leafcutter#81]
I've updated
```
[root@cri16cn021 example_data]# module list

Currently Loaded Modules:
  1) gcc/6.2.0   2) python/2.7.13   3) java-jdk/1.8.0_92   4) zlib/1.2.8   5) bzip2/1.0.6   6) xz/5.2.2   7) curl/7.51.0   8) pcre/8.39   9) R/3.3.2  10) perl/5.24.0  11) leafcutter

[root@cri16cn021 example_data]# R

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(leafcutter)
Loading required package: Rcpp
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux ComputeNode release 6.7 (Santiago)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] leafcutter_0.2.7 Rcpp_0.12.18    

loaded via a namespace (and not attached):
 [1] rstan_2.17.3        tidyselect_0.2.4    purrr_0.2.4        
 [4] reshape2_1.4.3      splines_3.3.2       lattice_0.20-35    
 [7] colorspace_1.3-2    htmltools_0.3.6     stats4_3.3.2       
[10] base64enc_0.1-3     survival_2.42-3     rlang_0.2.2        
[13] R.oo_1.22.0         pillar_1.2.2        foreign_0.8-70     
[16] glue_1.3.0          R.utils_2.7.0       RColorBrewer_1.1-2 
[19] bindrcpp_0.2.2      foreach_1.4.4       bindr_0.1.1        
[22] plyr_1.8.4          stringr_1.3.1       munsell_0.5.0      
[25] gtable_0.2.0        R.methodsS3_1.7.1   htmlwidgets_1.2    
[28] codetools_0.2-15    inline_0.3.14       latticeExtra_0.6-28
[31] knitr_1.20          htmlTable_1.11.2    acepack_1.4.1      
[34] scales_1.0.0        backports_1.1.2     checkmate_1.8.5    
[37] StanHeaders_2.17.2  Hmisc_4.1-1         gridExtra_2.3      
[40] ggplot2_3.0.0       digest_0.6.14       stringi_1.2.4      
[43] dplyr_0.7.6         grid_3.3.2          tools_3.3.2        
[46] magrittr_1.5        lazyeval_0.2.1      tibble_1.4.2       
[49] Formula_1.2-2       cluster_2.0.7-1     pkgconfig_2.0.2    
[52] Matrix_1.2-14       data.table_1.10.4-3 assertthat_0.2.0   
[55] rstudioapi_0.7      iterators_1.0.9     R6_2.2.2           
[58] rpart_4.1-13        intervals_0.15.1    nnet_7.3-12        
> quit()
Save workspace image? [y/n/c]: n
[root@cri16cn021 example_data]# python run_ds.py -A run/geuvadis/RNA.NA06984_CEU.chr1.bam,run/geuvadis/RNA.NA06985_CEU.chr1.bam,run/geuvadis/RNA.NA06986_CEU.chr1.bam,run/geuvadis/RNA.NA06989_CEU.chr1.bam -B run/geuvadis/RNA.NA18486_YRI.chr1.bam,run/geuvadis/RNA.NA18487_YRI.chr1.bam,run/geuvadis/RNA.NA18488_YRI.chr1.bam,run/geuvadis/RNA.NA18489_YRI.chr1.bam -d leafcutter/ -a ../clustering/gencode.v19.annotation.gtf.gz -t tmpdir
processing bam files...
tmpdir/RNA.NA06984_CEU.chr1.bam.junc exists..skipping
tmpdir/RNA.NA06985_CEU.chr1.bam.junc exists..skipping
tmpdir/RNA.NA06986_CEU.chr1.bam.junc exists..skipping
Running cmd: samtools view run/geuvadis/RNA.NA06989_CEU.chr1.bam | python leafcutter//scripts/filter_cs.py | leafcutter//scripts/sam2bed.pl --use-RNA-strand - tmpdir/RNA.NA06989_CEU.chr1.bam.bed
100000 valid, 0 problematic spliced reads
200000 valid, 0 problematic spliced reads
300000 valid, 0 problematic spliced reads
400000 valid, 0 problematic spliced reads
500000 valid, 0 problematic spliced reads
600000 valid, 0 problematic spliced reads

Running cmd: leafcutter//scripts/bed2junc.pl tmpdir/RNA.NA06989_CEU.chr1.bam.bed tmpdir/RNA.NA06989_CEU.chr1.bam.junc; rm tmpdir/RNA.NA06989_CEU.chr1.bam.bed

Running cmd: samtools view run/geuvadis/RNA.NA18486_YRI.chr1.bam | python leafcutter//scripts/filter_cs.py | leafcutter//scripts/sam2bed.pl --use-RNA-strand - tmpdir/RNA.NA18486_YRI.chr1.bam.bed
100000 valid, 0 problematic spliced reads
200000 valid, 0 problematic spliced reads
300000 valid, 0 problematic spliced reads
400000 valid, 0 problematic spliced reads
500000 valid, 0 problematic spliced reads
600000 valid, 0 problematic spliced reads
700000 valid, 0 problematic spliced reads
800000 valid, 0 problematic spliced reads
900000 valid, 0 problematic spliced reads
1000000 valid, 0 problematic spliced reads
1100000 valid, 0 problematic spliced reads
1200000 valid, 0 problematic spliced reads
1300000 valid, 0 problematic spliced reads

Running cmd: leafcutter//scripts/bed2junc.pl tmpdir/RNA.NA18486_YRI.chr1.bam.bed tmpdir/RNA.NA18486_YRI.chr1.bam.junc; rm tmpdir/RNA.NA18486_YRI.chr1.bam.bed

Running cmd: samtools view run/geuvadis/RNA.NA18487_YRI.chr1.bam | python leafcutter//scripts/filter_cs.py | leafcutter//scripts/sam2bed.pl --use-RNA-strand - tmpdir/RNA.NA18487_YRI.chr1.bam.bed
100000 valid, 0 problematic spliced reads
200000 valid, 0 problematic spliced reads
300000 valid, 0 problematic spliced reads
400000 valid, 0 problematic spliced reads
500000 valid, 0 problematic spliced reads
600000 valid, 0 problematic spliced reads
700000 valid, 0 problematic spliced reads

Running cmd: leafcutter//scripts/bed2junc.pl tmpdir/RNA.NA18487_YRI.chr1.bam.bed tmpdir/RNA.NA18487_YRI.chr1.bam.junc; rm tmpdir/RNA.NA18487_YRI.chr1.bam.bed

Running cmd: samtools view run/geuvadis/RNA.NA18488_YRI.chr1.bam | python leafcutter//scripts/filter_cs.py | leafcutter//scripts/sam2bed.pl --use-RNA-strand - tmpdir/RNA.NA18488_YRI.chr1.bam.bed
100000 valid, 0 problematic spliced reads
200000 valid, 0 problematic spliced reads
300000 valid, 0 problematic spliced reads
400000 valid, 0 problematic spliced reads
500000 valid, 0 problematic spliced reads

Running cmd: leafcutter//scripts/bed2junc.pl tmpdir/RNA.NA18488_YRI.chr1.bam.bed tmpdir/RNA.NA18488_YRI.chr1.bam.junc; rm tmpdir/RNA.NA18488_YRI.chr1.bam.bed

Running cmd: samtools view run/geuvadis/RNA.NA18489_YRI.chr1.bam | python leafcutter//scripts/filter_cs.py | leafcutter//scripts/sam2bed.pl --use-RNA-strand - tmpdir/RNA.NA18489_YRI.chr1.bam.bed
100000 valid, 0 problematic spliced reads
200000 valid, 0 problematic spliced reads
300000 valid, 0 problematic spliced reads
400000 valid, 0 problematic spliced reads
500000 valid, 0 problematic spliced reads
600000 valid, 0 problematic spliced reads
700000 valid, 0 problematic spliced reads
800000 valid, 0 problematic spliced reads
900000 valid, 0 problematic spliced reads

Running cmd: leafcutter//scripts/bed2junc.pl tmpdir/RNA.NA18489_YRI.chr1.bam.bed tmpdir/RNA.NA18489_YRI.chr1.bam.junc; rm tmpdir/RNA.NA18489_YRI.chr1.bam.bed

Running cmd: python leafcutter//clustering/leafcutter_cluster.py -j tmpdir/junction_files.txt -m 30 -o leafcutter -l 100000 -r tmpdir -p 0.001
scanning tmpdir/RNA.NA06984_CEU.chr1.bam.junc...
scanning tmpdir/RNA.NA06985_CEU.chr1.bam.junc...
scanning tmpdir/RNA.NA06986_CEU.chr1.bam.junc...
scanning tmpdir/RNA.NA06989_CEU.chr1.bam.junc...
scanning tmpdir/RNA.NA18486_YRI.chr1.bam.junc...
scanning tmpdir/RNA.NA18487_YRI.chr1.bam.junc...
scanning tmpdir/RNA.NA18488_YRI.chr1.bam.junc...
scanning tmpdir/RNA.NA18489_YRI.chr1.bam.junc...
Parsing...
chr1:NA..
Wrote 11463 clusters..
Split into 498 clusters...
Sorting tmpdir/RNA.NA06989_CEU.chr1.bam.junc..
Sorting tmpdir/RNA.NA18489_YRI.chr1.bam.junc..
Sorting tmpdir/RNA.NA18486_YRI.chr1.bam.junc..
Sorting tmpdir/RNA.NA06984_CEU.chr1.bam.junc..
Sorting tmpdir/RNA.NA06986_CEU.chr1.bam.junc..
Sorting tmpdir/RNA.NA18488_YRI.chr1.bam.junc..
Sorting tmpdir/RNA.NA18487_YRI.chr1.bam.junc..
Sorting tmpdir/RNA.NA06985_CEU.chr1.bam.junc..
merging 8 junction files...
merging 8 files done.

Running cmd: python leafcutter//clustering/get_cluster_gene.py ../clustering/gencode.v19.annotation.gtf.gz tmpdir/leafcutter_perind.counts.gz

Running cmd: Rscript leafcutter//scripts/leafcutter_ds.R --num_threads 1 -i 3 tmpdir/leafcutter_perind_numers.counts.gz tmpdir/ds_test
Loading required package: Rcpp
Loading required package: doMC
Loading required package: foreach
Loading required package: iterators
Loading required package: parallel
Error in mutate_impl(.data, dots) : 
  Evaluation error: object 'perturbed' not found.
Calls: leaf_cutter_effect_sizes ... <Anonymous> -> mutate -> mutate.tbl_df -> mutate_impl -> .Call
Execution halted

```

**Comment by stasaki** [comment]
I encountered the same error.

**Comment by davidaknowles** [comment]
I've pushed some changes that should make make the differential splicing pipeline more robust to this. Please can you reinstall `leafcutter` and see if it works now?

**Comment by davidaknowles** [comment]
I'm closing this for now, please feel free to reopen if the problem reappears.

**Comment by ecwheele** [comment]
I am getting this error using the leafcutter_ds.R script in leafcutter_0.2.8. Here is my session info: 

`> sessionInfo
function (package = NULL) 
{
    z <- list()
    z$R.version <- R.Version()
    z$platform <- z$R.version$platform
    if (nzchar(.Platform$r_arch)) 
        z$platform <- paste(z$platform, .Platform$r_arch, sep = "/")
    z$platform <- paste0(z$platform, " (", 8 * .Machine$sizeof.pointer, 
        "-bit)")
    z$locale <- Sys.getlocale()
    if (.Platform$OS.type == "windows") {
        z$running <- win.version()
    }
    else if (nzchar(Sys.which("uname"))) {
        uname <- system("uname -a", intern = TRUE)
        os <- sub(" .*", "", uname)
        z$running <- switch(os, Linux = if (file.exists("/etc/os-release")) {
            tmp <- readLines("/etc/os-release")
            t2 <- if (any(startsWith(tmp, "PRETTY_NAME="))) sub("^PRETTY_NAME=", 
                "", grep("^PRETTY_NAME=", tmp, value = TRUE)[1L]) else if (any(startsWith(tmp, 
                "NAME"))) sub("^NAME=", "", grep("^NAME=", tmp, 
                value = TRUE)[1L]) else "Linux (unknown distro)"
            sub("\"(.*)\"", "\\1", t2)
        } else if (file.exists("/etc/system-release")) {
            readLines("/etc/system-release")
        }, Darwin = {
            ver <- readLines("/System/Library/CoreServices/SystemVersion.plist")
            ind <- grep("ProductUserVisibleVersion", ver)
            ver <- ver[ind + 1L]
            ver <- sub(".*<string>", "", ver)
            ver <- sub("</string>$", "", ver)
            ver1 <- strsplit(ver, ".", fixed = TRUE)[[1L]][2L]
            sprintf("%s %s %s", ifelse(as.numeric(ver1) < 12, 
                "OS X", "macOS"), switch(ver1, `6` = "Snow Leopard", 
                `7` = "Lion", `8` = "Mountain Lion", `9` = "Mavericks", 
                `10` = "Yosemite", `11` = "El Capitan", `12` = "Sierra", 
                `13` = "High Sierra", ""), ver)
        }, SunOS = {
            ver <- system("uname -r", intern = TRUE)
            paste("Solaris", strsplit(ver, ".", fixed = TRUE)[[1L]][2L])
        }, uname)
    }
    if (is.null(package)) {
        package <- grep("^package:", search(), value = TRUE)
        keep <- vapply(package, function(x) x == "package:base" || 
            !is.null(attr(as.environment(x), "path")), NA)
        package <- .rmpkg(package[keep])
    }
    pkgDesc <- lapply(package, packageDescription, encoding = NA)
    if (length(package) == 0) 
        stop("no valid packages were specified")
    basePkgs <- sapply(pkgDesc, function(x) !is.null(x$Priority) && 
        x$Priority == "base")
    z$basePkgs <- package[basePkgs]
    if (any(!basePkgs)) {
        z$otherPkgs <- pkgDesc[!basePkgs]
        names(z$otherPkgs) <- package[!basePkgs]
    }
    loadedOnly <- loadedNamespaces()
    loadedOnly <- loadedOnly[!(loadedOnly %in% package)]
    if (length(loadedOnly)) {
        names(loadedOnly) <- loadedOnly
        pkgDesc <- c(pkgDesc, lapply(loadedOnly, packageDescription))
        z$loadedOnly <- pkgDesc[loadedOnly]
    }
    z$matprod <- as.character(options("matprod"))
    es <- extSoftVersion()
    z$BLAS <- as.character(es["BLAS"])
    z$LAPACK <- La_library()
    class(z) <- "sessionInfo"
    z
}
<bytecode: 0xa3e0178>
<environment: namespace:utils>
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS: /opt/conda/envs/r-leafcutter/lib/R/lib/libRblas.so
LAPACK: /opt/conda/envs/r-leafcutter/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] leafcutter_0.2.8     Rcpp_0.12.18         RevoUtils_11.0.1    
[4] RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] rstan_2.17.3        tidyselect_0.2.4    reshape2_1.4.3     
 [4] purrr_0.2.5         splines_3.5.1       lattice_0.20-35    
 [7] colorspace_1.3-2    stats4_3.5.1        htmltools_0.3.6    
[10] base64enc_0.1-3     survival_2.42-3     rlang_0.3.1        
[13] R.oo_1.22.0         pillar_1.3.0        foreign_0.8-70     
[16] glue_1.3.0          R.utils_2.6.0       RColorBrewer_1.1-2 
[19] bindrcpp_0.2.2      foreach_1.5.0       bindr_0.1.1        
[22] plyr_1.8.4          stringr_1.3.1       munsell_0.5.0      
[25] gtable_0.2.0        R.methodsS3_1.7.1   htmlwidgets_1.3    
[28] codetools_0.2-15    inline_0.3.15       latticeExtra_0.6-28
[31] knitr_1.20          rstantools_1.5.0    htmlTable_1.12     
[34] acepack_1.4.1       scales_0.5.0        backports_1.1.3    
[37] checkmate_1.8.5     StanHeaders_2.17.2  Hmisc_4.1-1        
[40] gridExtra_2.3       ggplot2_3.1.0       digest_0.6.15      
[43] stringi_1.2.4       dplyr_0.7.6         grid_3.5.1         
[46] tools_3.5.1         magrittr_1.5        lazyeval_0.2.1     
[49] tibble_1.4.2        Formula_1.2-3       cluster_2.0.7-1    
[52] crayon_1.3.4        pkgconfig_2.0.1     Matrix_1.2-14      
[55] data.table_1.11.4   assertthat_0.2.0    rstudioapi_0.9.0   
[58] iterators_1.0.10    R6_2.2.2            rpart_4.1-13       
[61] intervals_0.15.1    nnet_7.3-12         compiler_3.5.1   `

My command is: 

`leafcutter_ds.R --num_threads 4 --exon_file=~/software/leafcutter/leafcutter/data/gencode19_exons.txt.gz -i 2 -g 2 all_files_perind_numers.counts.gz groups_file.txt`

This is the output: 

`Loading required package: Rcpp
Loading counts from all_files_perind_numers.counts.gz 
Loading metadata from groups_file.txt 
Encoding as WT =0, Mut =1
Loading required package: doMC
Loading required package: foreach
Loading required package: iterators
Loading required package: parallel
Settings:
$output_prefix
[1] "leafcutter_ds"

$max_cluster_size
[1] Inf

$min_samples_per_intron
[1] 2

$min_samples_per_group
[1] 2

$min_coverage
[1] 20

$timeout
[1] 30

$num_threads
[1] 4

$exon_file
[1] "/home/ecwheele/software/leafcutter/leafcutter/data/gencode19_exons.txt.gz"

$init
[1] "smart"

$seed
[1] 12345

$help
[1] FALSE

Running differential splicing analysis...
Differential splicing summary:
                                             statuses Freq
1                          <=1 sample with coverage>0  168
2               <=1 sample with coverage>min_coverage  855
3 <2 introns used in >=min_samples_per_intron samples   73
4                            Not enough valid samples 7211
Saving results...
Loading exons from /home/ecwheele/software/leafcutter/leafcutter/data/gencode19_exons.txt.gz 
Error in mutate_impl(.data, dots) : 
  Evaluation error: object 'perturbed' not found.
Calls: leaf_cutter_effect_sizes ... <Anonymous> -> mutate -> mutate.tbl_df -> mutate_impl
Execution halted`

Any advice would be appreciated.

**Comment by katagirya** [comment]
> I am getting this error using the leafcutter_ds.R script in leafcutter_0.2.8. Here is my session info:
> 
> `> sessionInfo function (package = NULL) { z <- list() z$R.version <- R.Version() z$platform <- z$R.version$platform if (nzchar(.Platform$r_arch)) z$platform <- paste(z$platform, .Platform$r_arch, sep = "/") z$platform <- paste0(z$platform, " (", 8 * .Machine$sizeof.pointer, "-bit)") z$locale <- Sys.getlocale() if (.Platform$OS.type == "windows") { z$running <- win.version() } else if (nzchar(Sys.which("uname"))) { uname <- system("uname -a", intern = TRUE) os <- sub(" .*", "", uname) z$running <- switch(os, Linux = if (file.exists("/etc/os-release")) { tmp <- readLines("/etc/os-release") t2 <- if (any(startsWith(tmp, "PRETTY_NAME="))) sub("^PRETTY_NAME=", "", grep("^PRETTY_NAME=", tmp, value = TRUE)[1L]) else if (any(startsWith(tmp, "NAME"))) sub("^NAME=", "", grep("^NAME=", tmp, value = TRUE)[1L]) else "Linux (unknown distro)" sub("\"(.*)\"", "\\1", t2) } else if (file.exists("/etc/system-release")) { readLines("/etc/system-release") }, Darwin = { ver <- readLines("/System/Library/CoreServices/SystemVersion.plist") ind <- grep("ProductUserVisibleVersion", ver) ver <- ver[ind + 1L] ver <- sub(".*<string>", "", ver) ver <- sub("</string>$", "", ver) ver1 <- strsplit(ver, ".", fixed = TRUE)[[1L]][2L] sprintf("%s %s %s", ifelse(as.numeric(ver1) < 12, "OS X", "macOS"), switch(ver1, `6`= "Snow Leopard", `7`= "Lion",`8`= "Mountain Lion",`9`= "Mavericks", `10`= "Yosemite",`11`= "El Capitan",`12`= "Sierra", `13` = "High Sierra", ""), ver)
> }, SunOS = {
> ver <- system("uname -r", intern = TRUE)
> paste("Solaris", strsplit(ver, ".", fixed = TRUE)[[1L]][2L])
> }, uname)
> }
> if (is.null(package)) {
> package <- grep("^package:", search(), value = TRUE)
> keep <- vapply(package, function(x) x == "package:base" ||
> !is.null(attr(as.environment(x), "path")), NA)
> package <- .rmpkg(package[keep])
> }
> pkgDesc <- lapply(package, packageDescription, encoding = NA)
> if (length(package) == 0)
> stop("no valid packages were specified")
> basePkgs <- sapply(pkgDesc, function(x) !is.null(x$Priority) &&
> x$Priority == "base")
> z$basePkgs <- package[basePkgs]
> if (any(!basePkgs)) {
> z$otherPkgs <- pkgDesc[!basePkgs]
> names(z$otherPkgs) <- package[!basePkgs]
> }
> loadedOnly <- loadedNamespaces()
> loadedOnly <- loadedOnly[!(loadedOnly %in% package)]
> if (length(loadedOnly)) {
> names(loadedOnly) <- loadedOnly
> pkgDesc <- c(pkgDesc, lapply(loadedOnly, packageDescription))
> z$loadedOnly <- pkgDesc[loadedOnly]
> }
> z$matprod <- as.character(options("matprod"))
> es <- extSoftVersion()
> z$BLAS <- as.character(es["BLAS"])
> z$LAPACK <- La_library()
> class(z) <- "sessionInfo"
> z
> }
> <bytecode: 0xa3e0178>
> <environment: namespace:utils>
> 
> > sessionInfo()
> > R version 3.5.1 (2018-07-02)
> > Platform: x86_64-pc-linux-gnu (64-bit)
> > Running under: Debian GNU/Linux 9 (stretch)
> 
> Matrix products: default
> BLAS: /opt/conda/envs/r-leafcutter/lib/R/lib/libRblas.so
> LAPACK: /opt/conda/envs/r-leafcutter/lib/R/lib/libRlapack.so
> 
> locale:
> [1] LC_CTYPE=C.UTF-8 LC_NUMERIC=C LC_TIME=C.UTF-8
> [4] LC_COLLATE=C.UTF-8 LC_MONETARY=C.UTF-8 LC_MESSAGES=C.UTF-8
> [7] LC_PAPER=C.UTF-8 LC_NAME=C LC_ADDRESS=C
> [10] LC_TELEPHONE=C LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> [1] stats graphics grDevices utils datasets methods base
> 
> other attached packages:
> [1] leafcutter_0.2.8 Rcpp_0.12.18 RevoUtils_11.0.1
> [4] RevoUtilsMath_11.0.0
> 
> loaded via a namespace (and not attached):
> [1] rstan_2.17.3 tidyselect_0.2.4 reshape2_1.4.3
> [4] purrr_0.2.5 splines_3.5.1 lattice_0.20-35
> [7] colorspace_1.3-2 stats4_3.5.1 htmltools_0.3.6
> [10] base64enc_0.1-3 survival_2.42-3 rlang_0.3.1
> [13] R.oo_1.22.0 pillar_1.3.0 foreign_0.8-70
> [16] glue_1.3.0 R.utils_2.6.0 RColorBrewer_1.1-2
> [19] bindrcpp_0.2.2 foreach_1.5.0 bindr_0.1.1
> [22] plyr_1.8.4 stringr_1.3.1 munsell_0.5.0
> [25] gtable_0.2.0 R.methodsS3_1.7.1 htmlwidgets_1.3
> [28] codetools_0.2-15 inline_0.3.15 latticeExtra_0.6-28
> [31] knitr_1.20 rstantools_1.5.0 htmlTable_1.12
> [34] acepack_1.4.1 scales_0.5.0 backports_1.1.3
> [37] checkmate_1.8.5 StanHeaders_2.17.2 Hmisc_4.1-1
> [40] gridExtra_2.3 ggplot2_3.1.0 digest_0.6.15
> [43] stringi_1.2.4 dplyr_0.7.6 grid_3.5.1
> [46] tools_3.5.1 magrittr_1.5 lazyeval_0.2.1
> [49] tibble_1.4.2 Formula_1.2-3 cluster_2.0.7-1
> [52] crayon_1.3.4 pkgconfig_2.0.1 Matrix_1.2-14
> [55] data.table_1.11.4 assertthat_0.2.0 rstudioapi_0.9.0
> [58] iterators_1.0.10 R6_2.2.2 rpart_4.1-13
> [61] intervals_0.15.1 nnet_7.3-12 compiler_3.5.1 `
> 
> My command is:
> 
> `leafcutter_ds.R --num_threads 4 --exon_file=~/software/leafcutter/leafcutter/data/gencode19_exons.txt.gz -i 2 -g 2 all_files_perind_numers.counts.gz groups_file.txt`
> 
> This is the output:
> 
> `Loading required package: Rcpp
> Loading counts from all_files_perind_numers.counts.gz
> Loading metadata from groups_file.txt
> Encoding as WT =0, Mut =1
> Loading required package: doMC
> Loading required package: foreach
> Loading required package: iterators
> Loading required package: parallel
> Settings:
> $output_prefix
> [1] "leafcutter_ds"
> 
> $max_cluster_size
> [1] Inf
> 
> $min_samples_per_intron
> [1] 2
> 
> $min_samples_per_group
> [1] 2
> 
> $min_coverage
> [1] 20
> 
> $timeout
> [1] 30
> 
> $num_threads
> [1] 4
> 
> $exon_file
> [1] "/home/ecwheele/software/leafcutter/leafcutter/data/gencode19_exons.txt.gz"
> 
> $init
> [1] "smart"
> 
> $seed
> [1] 12345
> 
> $help
> [1] FALSE
> 
> Running differential splicing analysis...
> Differential splicing summary:
> statuses Freq
> 1 <=1 sample with coverage>0 168
> 2 <=1 sample with coverage>min_coverage 855
> 3 <2 introns used in >=min_samples_per_intron samples 73
> 4 Not enough valid samples 7211
> Saving results...
> Loading exons from /home/ecwheele/software/leafcutter/leafcutter/data/gencode19_exons.txt.gz
> Error in mutate_impl(.data, dots) :
> Evaluation error: object 'perturbed' not found.
> Calls: leaf_cutter_effect_sizes ... -> mutate -> mutate.tbl_df -> mutate_impl
> Execution halted`
> 
> Any advice would be appreciated.

@ecwheele I have a similar error, where you able to solve this? Thanks.
