### ISSUE TITLE
IndexError: too many indices for array (prepare_phenotype_table.py)

### ISSUE THREAD

**Issue by dfermin** [davidaknowles/leafcutter#82]
Hi

I'm trying to run the `prepare_phenotype_table.py` script on my data prior to fastQTL. However I keep getting this error when I run my command:
Traceback (most recent call last):

```
  File "/home/dfermin/apps/leafcutter/scripts/prepare_phenotype_table.py", line 171, in <module>

▽
    main(args[0], int(options.npcs) )
  File "/home/dfermin/apps/leafcutter/scripts/prepare_phenotype_table.py", line 117, in main
    for i in xrange(len(matrix[0,:])):
IndexError: too many indices for array
```
This is the command I'm executing on the terminal: 
`prepare_phenotype_table.py test_RNAseq_perind.counts.gz -p 10`

This is a sample of my *perind.counts.gz file in case it's a formatting issue:
```
chrom 526T.bam 13-527T.bam 428T.bam 725T.bam 15-1617T.bam 96T.bam
14:20813246:20813553:clu_1_NA 27/77 0/0 0/0 54/128 0/0 56/95
14:20813285:20813553:clu_1_NA 50/77 0/0 0/0 74/128 0/0 39/95
14:20923487:20923737:clu_2_NA 27/357 0/0 0/0 33/443 0/0 35/442
14:20923497:20923737:clu_2_NA 53/357 0/0 0/0 75/443 0/0 80/442
14:20923553:20923737:clu_2_NA 277/357 0/0 0/0 335/443 0/0 327/442
14:21152917:21161706:clu_3_NA 208/551 0/0 0/0 222/539 0/0 154/471
14:21152917:21167514:clu_3_NA 316/551 0/0 0/0 279/539 0/0 292/471
14:21161809:21167514:clu_3_NA 27/551 0/0 0/0 38/539 0/0 25/471
14:21270252:21270408:clu_4_NA 6/94 0/0 0/0 48/483 0/0 125/704
14:21270252:21270956:clu_4_NA 88/94 0/0 0/0 417/483 0/0 525/704
14:21270478:21270956:clu_4_NA 0/94 0/0 0/0 18/483 0/0 54/704
14:21490656:21491023:clu_5_NA 234/680 0/0 0/0 253/648 0/0 264/695
14:21490656:21491400:clu_5_NA 203/680 0/0 0/0 147/648 0/0 149/695
14:21491064:21491400:clu_5_NA 243/680 0/0 0/0 248/648 0/0 282/695
14:21491480:21492189:clu_6_NA 240/420 0/0 0/0 122/269 0/0 231/380
14:21491480:21493188:clu_6_NA 66/420 0/0 0/0 95/269 0/0 67/380
14:21492255:21493008:clu_6_NA 18/420 0/0 0/0 8/269 0/0 30/380
14:21492255:21493188:clu_6_NA 96/420 0/0 0/0 44/269 0/0 52/380
14:21679722:21679969:clu_7_NA 32/1602 0/0 0/0 55/2254 0/0 35/1430
14:21679725:21679969:clu_7_NA 1570/1602 0/0 0/0 2199/2254 0/0 1395/1430
14:21698525:21699117:clu_8_NA 229/1537 0/0 0/0 315/2262 0/0 410/2141
14:21698525:21699156:clu_8_NA 1308/1537 0/0 0/0 1947/2262 0/0 1731/2141
14:21702388:21730760:clu_9_NA 39/1961 0/0 0/0 38/2465 0/0 38/2306
14:21702388:21731470:clu_9_NA 878/1961 0/0 0/0 1094/2465 0/0 1034/2306
```
I can email someone the whole file if they want to take a look.
At first I thought it was because my chromosome labels didn't start with `chr` (eg: `chr14` instead of just `14` ) but changing that didn't fix the error. 

Any suggestions what I might be doing wrong?
I'm using Python 2.7 in case it matters.

Any and all help would be greatly appreciated!
Thanks,
Damian

**Comment by goldenflaw** [comment]
Yes, could you send it to me.

Best,
Yang

**Comment by dfermin** [comment]
[test_RNAseq_perind.counts.gz](https://github.com/davidaknowles/leafcutter/files/2465333/test_RNAseq_perind.counts.gz)

Here you go. 
Please let me know if you need anything else to debug this.

Thanks for your help!

**Comment by goldenflaw** [comment]
Hi Damian,

This is because you have too many 0/0 in your samples (for all introns).
prepare_phenotype_table prepares your data for QTL mapping if all introns
have >40% of samples missing data, this crashes. We will work in a warning
statement in the next revision. Thanks!

Best,
Yang

**Comment by goldenflaw** [comment]
It will work if you comment out these lines:

# If ratio is missing for over 40% of the samples, skip
        #if tmpvalRow.count("NA") > len(tmpvalRow)*0.4:
        #    continue

AND if you remove chromosomes that are non numeric (e.g. not 1 to 22).

Best,
Yang
