### ISSUE TITLE
Error in Splicing event visualization 

### ISSUE THREAD

**Issue by Wanpeng-Wang** [davidaknowles/leafcutter#83]
Relating to this issue. #80 
I downloaded the new code and the error message `nrow(exons_chr) > 0 is not TRUE` persists for all genes in Splicing event visualization window. 
I'm looking at Drosophila genome where chromosomes are "X", "Y", "2L", "2R", "3L", "3R", "4". The rownames of junction count matrix starts without "chr". I've checked in the leafviz.RData file, exons_table$chr starts without "chr". 
So `exons_chr <- exons_table[ exons_table$chr==intron_meta$chr[1], ]` should return something. 

I've tried to remove all "chr" characters in the following fields in the leafviz.RData 
```
clusters$coord <- gsub("chr", "", clusters$coord)
introns$chr <- gsub("chr", "", introns$chr)
```
and then I removed theses lines from make_cluster_plot.R,

```
# make sure intron_meta has "chr" in front of chromosome name so it plays nice with the exon table
  if( all( ! grepl("chr", intron_meta$chr))){
    intron_meta$chr <- paste0("chr", as.character(intron_meta$chr))
  }

  if(!is.null(exons_table)) {
    if( all(! grepl("chr", exons_table$chr))){
      exons_table$chr <- paste0("chr", as.character(exons_table$chr))
    }
  }
```
But the error persists. I'm out of ideas. 
Here is the link to my RData file. [https://www.dropbox.com/s/jp03sfkv52mto3z/leafviz.RData?dl=0](url)

Thank you!

Wanpeng

**Comment by jackhump** [comment]
Hi Wanpeng,

I'm sorry this has taken so long to respond. I'm intrigued by your problem. Can you reupload your Rdata file again please? I'll try and take a look.

**Comment by Wanpeng-Wang** [comment]
https://www.dropbox.com/s/2ewefhozc2q3sr4/GV_FC_leafviz.Rdata?dl=0

Thank you!

**Comment by jackhump** [comment]
This has now been fixed for the user. Reference #75
