### ISSUE TITLE
Extract split reads supporting a cluster

### ISSUE THREAD

**Issue by dfermin** [davidaknowles/leafcutter#84]
Hi
I'm trying to extract the reads that leafcutter uses in it's output `*_perind.counts.gz`. For instance I see this line in my data:
```
chrom samp1 samp2
14:20764605:20766956:clu_5_NA   147/336 203/411
```
This says that the first and second samples had 147 and 203 reads respectively supporting the cluster in my data set. 

But when I run samtools on these BAM files I can't get out those reads. 
I'm using `samtools view -f 256 samp1.bam 14:20764605-20766956` as the command to extract the reads. Perhaps this is the wrong command.

Could you advice on how to identify the reads of interest used by leafcutter?
In case it helps: my data is human paired-end RNAseq data aligned to GRCh37 using STAR 2.6.

Thanks in advance for any and all help.

**Comment by jackhump** [comment]
Hi,

Two possible issues with your command: 

1. your samtools command with -f 256 is specifying to only report reads that are not the primary alignment (see https://broadinstitute.github.io/picard/explain-flags.html).
If you want to do the opposite and only report uniquely mapping reads then you would use "-F 256" instead.

2. it could be the chromosome name. Double check what the chromosome names should look like by viewing a section of BAM file. The chromosome is the third column. It may be that you aligned your sample to a genome that uses "chr14" instead.

The larger issue here is that the coordinates "14:20764605-20766956" are the coordinates that span the junction. So using these coordinates with samtools will report all reads that overlap those coordinates, including the spliced reads.  
You can filter out just spliced reads that overlap this region with a little bit of AWK magic on the CIGAR string, the sixth column of the BAM file. If CIGAR string has an "N" character this means the read is split by the aligner.

Therefore you could do:

```
samtools view -F 256 samp1.bam 14:20764605-20766956 |
awk '$6 ~ /N/' 

```

This would print out all uniquely mapping 

My preferred method for doing this would be to load the BAM file into IGV and manually look at the reads there. IGV has a sashimi plot function which will clearly show you where the spliced junction reads are and how many are there, but the numbers will depend on what filtering IGV does, such as removing multi-mapping or low quality reads. You can change that in the settings.

I hope that's useful!

**Comment by jackhump** [comment]
Hi @dfermin , did this work for you? Can I close the issue now?

**Comment by dfermin** [comment]
Hi 
Yes sorry for the responding sooner. 
I was able to get out the split reads using your suggestion.

Thanks again!
