### ISSUE TITLE
Unable to get a working installation

### ISSUE THREAD

**Issue by agraubert** [davidaknowles/leafcutter#87]
I have tried multiple installation methods and I'm unable to get leafcutter to work.

I installed using your recommended `devtools::install_github` option, but the installation failed when compiling leafcutter:

```
In function `rstan::sample_writer_factory(std::ostream*, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, std::vector<unsigned long, std::allocator<unsigned long> > const&)':
/xchip/gtex/aarong/tmp/leafcutter/RLIB/rstan/include/rstan/rstan_writer.hpp:92: multiple definition of `rstan::sample_writer_factory(std::ostream*, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, std::vector<unsigned long, std::allocator<unsigned long> > const&)'
stan_files/bb_glm.o:/xchip/gtex/aarong/tmp/leafcutter/RLIB/rstan/include/rstan/rstan_writer.hpp:92: first defined here
stan_files/dm_glm.o: In function `rstan::sample_writer_factory(std::ostream*, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, std::vector<unsigned long, std::allocator<unsigned long> > const&)':
/xchip/gtex/aarong/tmp/leafcutter/RLIB/rstan/include/rstan/rstan_writer.hpp:92: multiple definition of `rstan::sample_writer_factory(std::ostream*, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, std::vector<unsigned long, std::allocator<unsigned long> > const&)'
stan_files/bb_glm.o:/xchip/gtex/aarong/tmp/leafcutter/RLIB/rstan/include/rstan/rstan_writer.hpp:92: first defined here
stan_files/dm_glm_multi_conc.o: In function `rstan::sample_writer_factory(std::ostream*, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, std::vector<unsigned long, std::allocator<unsigned long> > const&)':
/xchip/gtex/aarong/tmp/leafcutter/RLIB/rstan/include/rstan/rstan_writer.hpp:92: multiple definition of `rstan::sample_writer_factory(std::ostream*, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, std::vector<unsigned long, std::allocator<unsigned long> > const&)'
stan_files/bb_glm.o:/xchip/gtex/aarong/tmp/leafcutter/RLIB/rstan/include/rstan/rstan_writer.hpp:92: first defined here
stan_files/dm_glm_robust.o: In function `rstan::sample_writer_factory(std::ostream*, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, std::vector<unsigned long, std::allocator<unsigned long> > const&)':
/xchip/gtex/aarong/tmp/leafcutter/RLIB/rstan/include/rstan/rstan_writer.hpp:92: multiple definition of `rstan::sample_writer_factory(std::ostream*, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, std::vector<unsigned long, std::allocator<unsigned long> > const&)'
stan_files/bb_glm.o:/xchip/gtex/aarong/tmp/leafcutter/RLIB/rstan/include/rstan/rstan_writer.hpp:92: first defined here
collect2: error: ld returned 1 exit status
make: *** [leafcutter.so] Error 1
rm stan_files/dm_glm_robust.cc stan_files/bb_glm_fix_conc.cc stan_files/dm_glm_multi_conc.cc stan_files/bb_glm.cc stan_files/dm_glm.cc
ERROR: compilation failed for package 'leafcutter'
* removing '/xchip/gtex/aarong/tmp/leafcutter/RLIB/leafcutter'
Error: Command failed (1)
```

That seems to be an issue with the inclusion of rstan files, so I gave up and tried installing using conda, which actually works, but I'm unable to run `leafcutter_ds.R`:

```
Running differential splicing analysis...
Error in differential_splicing(counts, numeric_x, confounders = confounders,  : 
  unused arguments (init = opt$init, seed = opt$seed)
Execution halted
```

Any help you could provide, would be appreciated

**Comment by agraubert** [comment]
Additionally, after installing the conda package into an entirely new, empty conda environment, I get the following error when trying to run the package:
```
Loading required package: Rcpp
Error: package or namespace load failed for ‘leafcutter’:
 package ‘leafcutter’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
```

**Comment by agraubert** [comment]
After installing manually by checking out the repository and installing from source, I get yet another error:
```
Running differential splicing analysis...
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
Calls: differential_splicing -> get_intron_meta -> colnames<-
Execution halted
```

**Comment by SiyiWanggou** [comment]
I also meat this problem. How did you fix it,please?

**Comment by agraubert** [comment]
I wish I could help, but ultimately I could not get leafcutter to install successfully

**Comment by SiyiWanggou** [comment]
For the whole day, I fixed the installation problem. The leafcutter works on my PC.

**Comment by SiyiWanggou** [comment]
I installed leafcutter manually.
>conda create -n leafcutter
>source activate leafcutter
>conda install python=2
>conda install -c bioconda star
>conda install samtools
>conda install r=3.3.2
>conda install -c conda-forge readline=6.2
>conda install -c davidaknowles r-leafcutter # It didn't install the pacakge of leafcutter,but installed the dependent packages.
>conda update --all
>git clone https://github.com/davidaknowles/leafcutter
>cd leafcutter
>R
>>install.packages("roxygen2")
>>install.packages("rstantools")
>>install.packages("shinyjs")
>>install.packages("intervals")
>>q()
>R CMD INSTALL --build leafcutter

**Comment by agraubert** [comment]
Wow! Thanks for figuring this out. It's ridiculous how many hoops you had to jump through there

**Comment by SiyiWanggou** [comment]
Does it work on your computer?

**Comment by agraubert** [comment]
When I get to the `conda install -c davidaknowles r-leafcutter` step, it looks like it's upgrading R from 3.3.2 to 3.4.1-1

**Comment by agraubert** [comment]
I ran a quick test, and it does appear that it installed correctly. Thanks so much @SiyiWanggou!

Leaving the issue open because hopefully maintainers will update the conda recipe

**Comment by SiyiWanggou** [comment]
That's great! :)

**Comment by tkzeng** [comment]
Easier way to install using conda:
`conda` install -c r r=3.4.1
devtools::install_github("davidaknowles/leafcutter/leafcutter")`
(Earlier/later versions of R don't seem to work)

**Comment by yubailibra** [comment]
If you just need install the leafcutter package 
Here is what worked for me, similar to SiyiWanggou's solution but with some tweaks

conda create --name leafcutter
conda activate leafcutter
conda install -c r r  #this will install R 3.6.0 which is ok 
conda install -c davidaknowles r-leafcutter 
git clone https://github.com/davidaknowles/leafcutter
cd leafcutter
>R 
install.packages("roxygen2")
install.packages("rstantools")
install.packages("shinyjs")
install.packages("intervals")
q()

R CMD INSTALL --build leafcutter

**Comment by davidaknowles** [comment]
So the good news first: I think I've fixed the installation problems on newer R installs. This is updated in the online docs but TL;DR: 
```
devtools::install_github("stan-dev/rstantools")
devtools::install_github("davidaknowles/leafcutter/leafcutter")
```
You can also use `remotes` instead of `devtools` if you prefer, it's much lighter-weight. 

The bad news is the conda install is likely still broken. Setting this up originally was a huge pain and maintaining it also seems pretty bad since there's no automated way to have it pull from github afaik. Let me know if you'd really like a conda version and I can try to work out how to fix it up.

**Comment by aa-nava** [comment]
Installation using DavidaKnowles's conda instructions still do not work; encountering same issue reported here.

**Comment by katagirya** [comment]
> Installation using DavidaKnowles's conda instructions still does not work; encountering same issue reported here.

Same for me. I have spent weeks trying to trouble shoot but no success yet.

**Comment by aa-nava** [comment]
> > Installation using DavidaKnowles's conda instructions still does not work; encountering same issue reported here.
> 
> Same for me. I have spent weeks trying to trouble shoot but no success yet.

Same, I wasted 2-3 weeks of my life trying to install leafcutter using all the published install instructions on GitHub, but none worked for me... Ended up emailing the primary author to obtain an updated YML file, no response, so I ended up switching to a different splicing analysis software (called MAJIQ) that was easier to use and has better support/documentation.

**Comment by jackhump** [comment]
Dear @katagirya  and @aa-nava, our apologies for this. Leafcutter has unfortuately always been tricky to install correctly due to the large number of dependencies, epecially RStan, which has been a headache for all of us.  
As David said above we still don't have a fully working conda recipe. I know you've both tried a bunch of different ways to do but can I trouble you to try one final time? This is what I ended up having to do to get it on my cluster:

```
remotes::install_github("stan-dev/rstantools")
remotes::install_github("davidaknowles/leafcutter/leafcutter", ref = "psi_2019")
```

If this fails please paste up the error message on this thread and I'll try to troubleshoot.

**Comment by katagirya** [comment]
Thanks Jack,
Do you recommend any particular R version? I am going to try this
installation and will let you know what happens.

Eric

**Comment by jackhump** [comment]
Yes I should've said this worked in R 3.6.0. Good luck!

**Comment by katagirya** [comment]
Hi @jackhump the installation worked for me. I had to use an older version of "Rcpp".

> Dear @katagirya and @aa-nava, our apologies for this. Leafcutter has unfortuately always been tricky to install correctly due to the large number of dependencies, epecially RStan, which has been a headache for all of us.
> As David said above we still don't have a fully working conda recipe. I know you've both tried a bunch of different ways to do but can I trouble you to try one final time? This is what I ended up having to do to get it on my cluster:
> 
> ```
> remotes::install_github("stan-dev/rstantools")
> remotes::install_github("davidaknowles/leafcutter/leafcutter", ref = "psi_2019")
> ```
> 
> If this fails please paste up the error message on this thread and I'll try to troubleshoot.

Hi @jackhump this worked for me. I had to use an older version of "Rccp" and R=3.6.0.
Thanks.

**Comment by Aynur31** [comment]
> I installed leafcutter manually.
> 
> > conda create -n leafcutter
> > source activate leafcutter
> > conda install python=2
> > conda install -c bioconda star
> > conda install samtools
> > conda install r=3.3.2
> > conda install -c conda-forge readline=6.2
> > conda install -c davidaknowles r-leafcutter # It didn't install the pacakge of leafcutter,but installed the dependent packages.
> > conda update --all
> > git clone https://github.com/davidaknowles/leafcutter
> > cd leafcutter
> 
> > R
> > > install.packages("roxygen2")
> > > install.packages("rstantools")
> > > install.packages("shinyjs")
> > > install.packages("intervals")
> > > q()
> 
> > R CMD INSTALL --build leafcutter

Hello , 
Thank you for the kind help. 
I used the same code for this starting from creating a new conda envi on linux 68 cluster. 
But I got the following errors -  even after installing these packages. 
Error: depencies 'rstan','Hmisc' 'shinycssloader'
