### ISSUE TITLE
How can I get PSI for sample-level?

### ISSUE THREAD

**Issue by zhengjiantao** [davidaknowles/leafcutter#89]
I have already finished step 2: define intron clustering
and I want to get the PSI for per sample?
How can I don that?
Thanks advanced!

**Comment by davidaknowles** [comment]
This isn't something that leafcutter usually outputs on the basis it would be pretty noisy. We do however use it for the sQTL analysis so you can use the script described here: 
http://davidaknowles.github.io/leafcutter/articles/sQTL.html
Note you may not want to remove any PCs if you just want to look at the raw ratios.
