### ISSUE TITLE
genotype file in sQTL analysis

### ISSUE THREAD

**Issue by CLeib** [davidaknowles/leafcutter#90]
Hello,

Can someone please advise me how to prepare the VCF genotype file for the sQTL analysis? 

Thanks in advance!

**Comment by goldenflaw** [comment]
See http://fastqtl.sourceforge.net/.

Best,
Yang

**Comment by CLeib** [comment]
Hi Yang,

Thank you for your reply! I may have misphrased the question. What I meant to ask is how do I get the VCF file in the first place, before preparing it for the sQTL analysis. Is it an output from LeafCutter, or is there some other recommended way of making it from the data?

Thanks again

**Comment by goldenflaw** [comment]
No, you obtain the VCF files from either calling SNPs using genotyping
arrays, DNA-seq, or RNA-seq and imputing.

Best,
Yang

**Comment by CLeib** [comment]
Alright, Thanks
