### ISSUE TITLE
maximum intron length default value 

### ISSUE THREAD

**Issue by gouthamatla** [davidaknowles/leafcutter#91]
Hi,

I would like to know why the maximum intron length is set to 100kb. There can be many introns in human genome that could span > 100kb.

I would like to know what are the consequences of changing this value ?

Thanks,
Goutham A

**Comment by goldenflaw** [comment]
You can change it to a larger number. The consequence is that the clusters
will sometimes be very large with many introns clustering together that are
far away.

Best,
Yang
