### ISSUE TITLE
Filtering results on leafviz

### ISSUE THREAD

**Issue by pabbm** [davidaknowles/leafcutter#92]
I've been able to run everything quite easily. However, when trying to visualize my results I found too many clusters to analyse. Is there anyway to set a filter on leafviz so I can filter by PSI or q-value? 
Thanks!
Pablo

**Comment by jackhump** [comment]
Hi Pablo,
Too many significant clusters sounds like a good problem to have! 😄 

When you create the leafviz input file with prepare_results.R you can specify an FDR (q-value) cut-off. The default is 0.05 but you can go lower with the --FDR flag.

As for filtering by PSI that's an interesting suggestion and something we should look into.

If you're handy with R you can load in the leafviz Rdata file into an R session and play with the tables in there. The delta PSI values for each junction are stored in a table called "introns" and the results per cluster are stored in a table called "clusters". 

Happy exploring!
