### ISSUE TITLE
Installation steps suggestion

### ISSUE THREAD

**Issue by pcarbo** [davidaknowles/leafcutter#95]
Hi Yang &  David,

Briana & I are currently working on installing leafcutter. Unfortunately, your conda environment doesn't quite work---I didn't look into how you set it up, but we are having issues that the R packages under different versions of R than the R that was installed.

My suggestion is to make installation of rstan a separate installation step, and as early on as possible. This is by far the most difficult installation step (in particular, it requires installing C++14-compliant compilers, figuring out how to set up R to build packages from source, and perhaps rebuilding R from source depending on your OS); I suggest pointing to the rstan documentation. Once rstan is installed, everything else should be relatively smooth.

**Comment by davidaknowles** [comment]
Hi Peter - sorry for the super delayed response. Starting a lab isn't very conducive to fixing github issues it seems. This is a great idea, thanks. 

And yeah, getting conda to work originally on my system was a struggle, maybe we should just deprecate that installation option for now.

**Comment by davidaknowles** [comment]
Ok I've linked to the `rstan` installation instructions and pointed out that you don't actually need to do this if you're just going to do sQTLs or something else with the raw count matrix.
