### ISSUE TITLE
Problem with tutorial dataset

### ISSUE THREAD

**Issue by cristian2420** [davidaknowles/leafcutter#97]
Hi Yang & David,

I'm trying to replicate your tutorial example, but your dataset is not available in the script´s link. Could you help? 
:)

**Comment by mbosio85** [comment]
Hello,
We have the same problem here, is there another way to get it and run some test? 
Thanks!
Mattia

**Comment by SiyiWanggou** [comment]
I also found the link is out.

**Comment by gonzalobenegas** [comment]
I've found a working link here:
https://github.com/davidaknowles/leafcutter/blob/master/example_data/python_wrappers.sh

```wget https://www.dropbox.com/s/pni1zq5y6cr4tx5/example_geuvadis.tar.gz?dl=0 -O example_geuvadis.tar.gz```

**Comment by davidaknowles** [comment]
I've fixed the link in the other script too now.
