### ISSUE TITLE
-g -i

### ISSUE THREAD

**Issue by JieqiangHe** [davidaknowles/leafcutter#99]
Dear all
I like this tool a lot and i decide to use this tool as my alternative splicing analysis tools in my paper.
but I don't understand the parameters of '- g' & '- i' in this tools.
Actually, i want to compare two different treatments, each on with three samples. <3 versus 3>

I used to use '-g 3 -i 3' in my command but i dont understand this part.

> -i (minimum samples per intron) and -g (minimum samples per group)

I know '-g' should be 3, what about '-i'?  3 or 6? Can someone explain to me.

I will appreciate you very much!
Thanks a lot!
Hoping for your reply.

**Comment by SiyiWanggou** [comment]
I also have 3 versus 3 expriment design. 
The author mentioned "Proceed with caution if you have fewer than 4 samples per group. Such analyses can be performed changing the -i (minimum samples per intron) and -g (minimum samples per group) options in leafcutter_ds.R, e.g. -i 4 -g 2 for 2 versus 2 comparisons (default is currently -i 5 -g 3). "
I think for 3 versus 3 design, '-g' & '-i‘ should be -i 6 & -g 3. It may means that for each intron, we (should) have 6 samples and for each group, we (should) have 3 samples.
I don't know whether my understanding is correct or not.

**Comment by JieqiangHe** [comment]
I got the suggestion from the writer, he suggested me use a small -i, e.g 2 to filter post-hoc. What do you think?

**Comment by davidaknowles** [comment]
The `-i min_samples_per_intron` filter is applied first. For an intron (junction) to be included in the analysis it needs to have non-zero counts in at least `min_samples_per_intron` samples. 
The `-g min_samples_per_group` is next. For the cluster to be tested for DS at each group must have at least `min_samples_per_group` samples with coverage over `min_coverage` (default 20). 
Hope this helps. I'll add this explanation to `leafcutter_ds.R` docs.
